import { resolveAppConfig } from "@repo/lib";

export const albionOnline = resolveAppConfig({
  name: "albion-online",
  // The game's own localization (Arabic not shipped yet).
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "it",
    "pl",
    "pt-BR",
    "ru",
    "tr",
    "id",
    "ja",
    "ko",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  withoutLiveMode: true,
  // No manual "/maps/..." internalLinks — the home page auto-generates the map
  // cards from version.data.tiles. The links below point at the database.
  internalLinks: [
    {
      title: "Zones",
      description:
        "Every zone of Albion — tier, PvP rules, biome, which resources spawn there, its mobs and neighbouring zones, with an interactive map.",
      href: "/db/locations",
      iconName: "Map",
      linkText: "Browse all zones",
    },
    {
      title: "Mobs",
      description:
        "The Albion bestiary: health, damage, resistances, fame and every zone a mob spawns in.",
      href: "/db/mobs",
      iconName: "Bug",
      linkText: "Open the bestiary",
    },
    {
      title: "Weapons",
      description:
        "All weapons by tier with item power, crafting recipes and enchantment upgrades.",
      href: "/db/weaponry",
      iconName: "Axe",
      linkText: "Browse weapons",
    },
    {
      title: "Armor",
      description:
        "Helmets, chest armor and shoes for cloth, leather and plate.",
      href: "/db/armor",
      iconName: "Shield",
      linkText: "Browse armor",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  externalLinks: [],
  keywords: ["Zone Maps", "Resources", "Dungeons", "Roads of Avalon"],
  topFilters: [
    "zone_exit",
    "dungeon_entrance",
    "ore_t6",
    "bank",
    "chest_boss",
    "bosses",
  ],
  db: {
    heroSubtitle: "Game Database",
    searchPlaceholder: "Search zones, mobs, items…",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/locations",
        type: "locations",
        titleFallback: "Zones",
        icon: "🗺️",
        description: "Every zone with its resources, mobs and map.",
      },
      {
        href: "/db/mobs",
        type: "mobs",
        titleFallback: "Mobs",
        icon: "💀",
        description: "Stats and spawn zones of every mob.",
      },
      {
        href: "/db/weaponry",
        type: "weaponry",
        titleFallback: "Weapons",
        icon: "⚔️",
        description: "Weapons with recipes and enchantments.",
      },
      {
        href: "/db/armor",
        type: "armor",
        titleFallback: "Armor",
        icon: "🛡️",
        description: "Cloth, leather and plate armor.",
      },
      {
        href: "/db/offhands",
        type: "offhands",
        titleFallback: "Off-Hands",
        icon: "📕",
        description: "Shields, tomes, torches and more.",
      },
      {
        href: "/db/accessories",
        type: "accessories",
        titleFallback: "Capes & Bags",
        icon: "🎒",
        description: "Capes and bags.",
      },
      {
        href: "/db/mounts",
        type: "mounts",
        titleFallback: "Mounts",
        icon: "🐎",
        description: "Every mount with speed and load.",
      },
      {
        href: "/db/consumables",
        type: "consumables",
        titleFallback: "Consumables",
        icon: "🧪",
        description: "Food and potions.",
      },
      {
        href: "/db/materials",
        type: "materials",
        titleFallback: "Resources & Materials",
        icon: "🪵",
        description: "Raw and refined resources.",
      },
      {
        href: "/db/artefacts",
        type: "artefacts",
        titleFallback: "Artifacts",
        icon: "💎",
        description: "Artifacts for artifact gear.",
      },
      {
        href: "/db/gathering-gear",
        type: "gathering-gear",
        titleFallback: "Gathering Gear",
        icon: "⛏️",
        description: "Tools and gathering outfits.",
      },
      {
        href: "/db/farming",
        type: "farming",
        titleFallback: "Farming",
        icon: "🌾",
        description: "Seeds, crops and animals.",
      },
      {
        href: "/db/furniture",
        type: "furniture",
        titleFallback: "Furniture",
        icon: "🪑",
        description: "Furniture for houses and islands.",
      },
    ],
    typeLabels: {
      locations: "Zone",
      mobs: "Mob",
      weaponry: "Weapon",
      armor: "Armor",
      offhands: "Off-Hand",
      accessories: "Accessory",
      mounts: "Mount",
      consumables: "Consumable",
      materials: "Material",
      artefacts: "Artifact",
      "gathering-gear": "Gathering Gear",
      farming: "Farming",
      furniture: "Furniture",
      vanity: "Vanity",
      misc: "Item",
    },
  },
});
