import { resolveAppConfig } from "@repo/lib";

export const albionOnline = resolveAppConfig({
  name: "albion-online",
  // The game's own localization (Arabic not shipped yet).
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "it",
    "pl",
    "pt-BR",
    "ru",
    "tr",
    "id",
    "ja",
    "ko",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  withoutLiveMode: true,
  // Market prices in the crafting calculator (Albion Online Data Project).
  craftingMarket: "aodp",
  // No manual "/maps/..." internalLinks — the home page auto-generates the map
  // cards from version.data.tiles. The links below point at the database.
  internalLinks: [
    {
      title: "config.internalLinks.locations.title",
      description: "config.internalLinks.locations.description",
      href: "/db/locations",
      iconName: "Map",
      linkText: "config.internalLinks.locations.linkText",
    },
    {
      title: "config.internalLinks.mobs.title",
      description: "config.internalLinks.mobs.description",
      href: "/db/mobs",
      iconName: "Bug",
      linkText: "config.internalLinks.mobs.linkText",
    },
    {
      title: "config.internalLinks.weaponry.title",
      description: "config.internalLinks.weaponry.description",
      href: "/db/weaponry",
      iconName: "Axe",
      linkText: "config.internalLinks.weaponry.linkText",
    },
    {
      title: "config.internalLinks.armor.title",
      description: "config.internalLinks.armor.description",
      href: "/db/armor",
      iconName: "Shield",
      linkText: "config.internalLinks.armor.linkText",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  externalLinks: [],
  keywords: ["Zone Maps", "Resources", "Dungeons", "Roads of Avalon"],
  topFilters: [
    "zone_exit",
    "dungeon_entrance",
    "ore_t6",
    "bank",
    "chest_boss",
    "bosses",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/locations",
        type: "locations",
        titleKey: "config.internalLinks.locations.title",
        titleFallback: "Zones",
        icon: "🗺️",
        description: "config.db.locations.description",
      },
      {
        href: "/db/mobs",
        type: "mobs",
        titleKey: "config.internalLinks.mobs.title",
        titleFallback: "Mobs",
        icon: "💀",
        description: "config.db.mobs.description",
      },
      {
        href: "/db/weaponry",
        type: "weaponry",
        titleKey: "config.internalLinks.weaponry.title",
        titleFallback: "Weapons",
        icon: "⚔️",
        description: "config.db.weaponry.description",
      },
      {
        href: "/db/armor",
        type: "armor",
        titleKey: "config.internalLinks.armor.title",
        titleFallback: "Armor",
        icon: "🛡️",
        description: "config.db.armor.description",
      },
      {
        href: "/db/offhands",
        type: "offhands",
        titleKey: "config.db.offhands.title",
        titleFallback: "Off-Hands",
        icon: "📕",
        description: "config.db.offhands.description",
      },
      {
        href: "/db/accessories",
        type: "accessories",
        titleKey: "config.db.accessories.title",
        titleFallback: "Capes & Bags",
        icon: "🎒",
        description: "config.db.accessories.description",
      },
      {
        href: "/db/mounts",
        type: "mounts",
        titleKey: "config.db.mounts.title",
        titleFallback: "Mounts",
        icon: "🐎",
        description: "config.db.mounts.description",
      },
      {
        href: "/db/consumables",
        type: "consumables",
        titleKey: "config.db.consumables.title",
        titleFallback: "Consumables",
        icon: "🧪",
        description: "config.db.consumables.description",
      },
      {
        href: "/db/materials",
        type: "materials",
        titleKey: "config.db.materials.title",
        titleFallback: "Resources & Materials",
        icon: "🪵",
        description: "config.db.materials.description",
      },
      {
        href: "/db/artefacts",
        type: "artefacts",
        titleKey: "config.db.artefacts.title",
        titleFallback: "Artifacts",
        icon: "💎",
        description: "config.db.artefacts.description",
      },
      {
        href: "/db/gathering-gear",
        type: "gathering-gear",
        titleKey: "config.db.gathering-gear.title",
        titleFallback: "Gathering Gear",
        icon: "⛏️",
        description: "config.db.gathering-gear.description",
      },
      {
        href: "/db/farming",
        type: "farming",
        titleKey: "config.db.farming.title",
        titleFallback: "Farming",
        icon: "🌾",
        description: "config.db.farming.description",
      },
      {
        href: "/db/furniture",
        type: "furniture",
        titleKey: "config.db.furniture.title",
        titleFallback: "Furniture",
        icon: "🪑",
        description: "config.db.furniture.description",
      },
      {
        href: "/db/vanity",
        type: "vanity",
        titleKey: "config.db.vanity.title",
        titleFallback: "Vanity",
        icon: "👑",
        description: "config.db.vanity.description",
      },
      {
        href: "/db/misc",
        type: "misc",
        titleKey: "config.db.misc.title",
        titleFallback: "Other Items",
        icon: "📦",
        description: "config.db.misc.description",
      },
      {
        href: "/db/abilities",
        type: "abilities",
        titleKey: "config.db.abilities.title",
        titleFallback: "Abilities",
        icon: "✨",
        description: "config.db.abilities.description",
      },
    ],
    typeLabels: {
      locations: "config.db.typeLabels.locations",
      mobs: "config.db.typeLabels.mobs",
      weaponry: "config.db.typeLabels.weaponry",
      armor: "config.db.typeLabels.armor",
      offhands: "config.db.typeLabels.offhands",
      accessories: "config.db.typeLabels.accessories",
      mounts: "config.db.typeLabels.mounts",
      consumables: "config.db.typeLabels.consumables",
      materials: "config.db.typeLabels.materials",
      artefacts: "config.db.typeLabels.artefacts",
      "gathering-gear": "config.db.typeLabels.gathering-gear",
      farming: "config.db.typeLabels.farming",
      furniture: "config.db.typeLabels.furniture",
      vanity: "config.db.typeLabels.vanity",
      misc: "config.db.typeLabels.misc",
      abilities: "config.db.typeLabels.abilities",
    },
  },
});
