import { resolveAppConfig } from "@repo/lib";

export const aniimo = resolveAppConfig({
  name: "aniimo",
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "id",
    "ja",
    "ko",
    "pt",
    "ru",
    "th",
    "vi",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "tb.title",
      description: "config.internalLinks.team-builder.description",
      href: "/team-builder",
      bgImage: "/games/thgl-web/tools/team-builder.webp",
      iconName: "Users",
      linkText: "config.internalLinks.team-builder.linkText",
    },
    {
      title: "evo.navTitle",
      description: "evo.navDescription",
      href: "/evolutions",
      bgImage: "/games/thgl-web/tools/evolutions.webp",
      iconName: "Sparkles",
      linkText: "evo.navLinkText",
    },
    {
      title: "prismana.navTitle",
      description: "prismana.navDescription",
      href: "/prismana",
      bgImage: "/games/thgl-web/tools/prismana.webp",
      iconName: "Flower",
      linkText: "prismana.navLinkText",
    },
    {
      href: "/activities-tracker",
      title: "activities.navTitle",
      description: "activities.navDescription",
      linkText: "activities.navLinkText",
      iconName: "Activity",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Aniimo Spawns",
    "Chests",
    "Lumin Amber",
    "Transporters",
    "Sanctums",
    "Alpha & Omega",
  ],
  topFilters: [
    "transporter",
    "sanctum",
    "alpha",
    "chest_advanced",
    "lumin_amber",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    // One indexable /team-builder/<id> matchup page and /evolutions/<id> evolution page
    // per Aniimo (sitemap + codex link).
    entryPages: [
      { type: "aniimo", path: "/team-builder", labelKey: "tb.entry.label" },
      { type: "aniimo", path: "/evolutions", labelKey: "evo.entry.label" },
    ],
    homeSections: [
      {
        href: "/db/aniimo",
        type: "aniimo",
        titleKey: "config.db.aniimo.title",
        titleFallback: "Aniimo",
        icon: "🐾",
        description: "config.db.aniimo.description",
      },
      {
        href: "/db/items",
        type: "items",
        titleKey: "config.db.items.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.items.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.db.recipes.title",
        titleFallback: "Recipes",
        icon: "🍳",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/skills",
        type: "skills",
        titleKey: "config.db.skills.title",
        titleFallback: "Skills",
        icon: "✨",
        description: "config.db.skills.description",
      },
      {
        href: "/db/talents",
        type: "talents",
        titleKey: "config.db.talents.title",
        titleFallback: "Talents",
        icon: "🧬",
        description: "config.db.talents.description",
      },
      {
        href: "/db/type_chart",
        type: "type_chart",
        titleKey: "config.db.type_chart.title",
        titleFallback: "Type Chart",
        icon: "⚔️",
        description: "config.db.type_chart.description",
      },
      {
        href: "/db/roles",
        type: "roles",
        titleKey: "config.db.roles.title",
        titleFallback: "Roles",
        icon: "🛡️",
        description: "config.db.roles.description",
      },
      {
        href: "/db/shops",
        type: "shops",
        titleKey: "config.db.shops.title",
        titleFallback: "Shops",
        icon: "🛒",
        description: "config.db.shops.description",
      },
      {
        href: "/db/quests",
        type: "quests",
        titleKey: "config.db.quests.title",
        titleFallback: "Quests",
        icon: "📜",
        description: "config.db.quests.description",
      },
      {
        href: "/db/badges",
        type: "badges",
        titleKey: "config.db.badges.title",
        titleFallback: "Badges",
        icon: "🏅",
        description: "config.db.badges.description",
      },
    ],
  },
});
