import { resolveAppConfig } from "@repo/lib";

export const baldursGateEE = resolveAppConfig({
  name: "baldurs-gate-ee",
  // Every language the game ships a dialog.tlk for (data-forge emits all 15).
  supportedLocales: [
    "en",
    "cs",
    "de",
    "es",
    "fr",
    "hu",
    "it",
    "ja",
    "ko",
    "pl",
    "pt-BR",
    "ru",
    "tr",
    "uk",
    "zh-CN",
  ],
  appUrl: "https://www.th.gl/companion-app",
  // No manual "/maps/..." internalLinks — the home page auto-generates the map
  // cards from version.data.tiles. The links below point at the database.
  internalLinks: [
    {
      title: "config.internalLinks.inventory.title",
      description: "config.internalLinks.inventory.description",
      href: "/db/inventory",
      iconName: "Shield",
      linkText: "config.internalLinks.inventory.linkText",
    },
    {
      title: "config.internalLinks.bestiary.title",
      description: "config.internalLinks.bestiary.description",
      href: "/db/bestiary",
      iconName: "Bug",
      linkText: "config.internalLinks.bestiary.linkText",
    },
    {
      title: "config.internalLinks.spells.title",
      description: "config.internalLinks.spells.description",
      href: "/db/spells",
      iconName: "Sparkles",
      linkText: "config.internalLinks.spells.linkText",
    },
    {
      title: "config.internalLinks.stores.title",
      description: "config.internalLinks.stores.description",
      href: "/db/stores",
      iconName: "MapPin",
      linkText: "config.internalLinks.stores.linkText",
    },
  ],
  externalLinks: [],
  keywords: [
    "Sword Coast",
    "Siege of Dragonspear",
    "Containers",
    "Traps",
    "Secret Doors",
    "Companions",
    "Merchants",
    "Area Exits",
  ],
  topFilters: [
    "exit",
    "container",
    "companion",
    "store",
    "trap",
    "secret_door",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    groupHeaderSections: ["characters", "quests"],
    homeSections: [
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "config.internalLinks.inventory.title",
        titleFallback: "Items",
        icon: "🗡️",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/spells",
        type: "spells",
        titleKey: "config.internalLinks.spells.title",
        titleFallback: "Spells",
        icon: "✨",
        description: "config.db.spells.description",
      },
      {
        href: "/db/bestiary",
        type: "bestiary",
        titleKey: "config.internalLinks.bestiary.title",
        titleFallback: "Bestiary",
        icon: "🐺",
        description: "config.db.bestiary.description",
      },
      {
        href: "/db/characters",
        type: "characters",
        titleKey: "config.db.characters.title",
        titleFallback: "Characters",
        icon: "🧝",
        description: "config.db.characters.description",
      },
      {
        href: "/db/quests",
        type: "quests",
        titleKey: "config.db.quests.title",
        titleFallback: "Quests",
        icon: "📜",
        description: "config.db.quests.description",
      },
      {
        href: "/db/stores",
        type: "stores",
        titleKey: "config.internalLinks.stores.title",
        titleFallback: "Stores",
        icon: "🛒",
        description: "config.db.stores.description",
      },
    ],
    typeLabels: {
      inventory: "config.db.typeLabels.inventory",
      spells: "config.db.typeLabels.spells",
      bestiary: "config.db.typeLabels.bestiary",
      characters: "config.db.typeLabels.characters",
      stores: "config.db.typeLabels.stores",
      quests: "config.db.typeLabels.quests",
    },
  },
});
