import { resolveAppConfig, DATA_FORGE_CDN_URL } from "@repo/lib";

// Inlined per-map preview URLs; the originals used getPreviewImageUrl()
// which would drag cbor-x into middleware via @repo/lib.
const preview = (mapId: string) =>
  `${DATA_FORGE_CDN_URL}/blue-protocol-star-resonance/map-tiles/${mapId}/preview.webp`;

export const blueProtocolStarResonance = resolveAppConfig({
  name: "blue-protocol-star-resonance",
  supportedLocales: ["en", "ja", "zh-CN", "zh-TW", "th"],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "Asteria Plains Map",
      description: "config.internalLinks.maps-Asteria%20Plains.description",
      href: "/maps/Asteria%20Plains",
      iconName: "Map",
      bgImage: preview("asteria_plains"),
      linkText: "config.internalLinks.maps-Asteria%20Plains.linkText",
    },
    {
      title: "Asterleeds Map",
      description: "config.internalLinks.maps-Asterleeds.description",
      href: "/maps/Asterleeds",
      iconName: "Map",
      bgImage: preview("asterleeds"),
      linkText: "config.internalLinks.maps-Asterleeds.linkText",
    },
    {
      title: "Moonshadow Wilds Map",
      description: "config.internalLinks.maps-Moonshadow%20Wilds.description",
      href: "/maps/Moonshadow%20Wilds",
      iconName: "Map",
      bgImage: preview("moonshadow_wilds"),
      linkText: "config.internalLinks.maps-Moonshadow%20Wilds.linkText",
    },
    {
      title: "Bahamar Highlands Map",
      description: "config.internalLinks.maps-Bahamar%20Highlands.description",
      href: "/maps/Bahamar%20Highlands",
      iconName: "Map",
      bgImage: preview("bahamar_highlands"),
      linkText: "config.internalLinks.maps-Bahamar%20Highlands.linkText",
    },
    {
      title: "Bahamar Highlands (Deepreach) Map",
      description:
        "config.internalLinks.maps-Bahamar%20Highlands%20(Deepreach).description",
      href: "/maps/Bahamar%20Highlands%20(Deepreach)",
      iconName: "Map",
      bgImage: preview("bahamar_highlands_deepreach"),
      linkText:
        "config.internalLinks.maps-Bahamar%20Highlands%20(Deepreach).linkText",
    },
    {
      title: "Windhowl Canyon Map",
      description: "config.internalLinks.maps-Windhowl%20Canyon.description",
      href: "/maps/Windhowl%20Canyon",
      iconName: "Map",
      bgImage: preview("windhowl_canyon"),
      linkText: "config.internalLinks.maps-Windhowl%20Canyon.linkText",
    },
    {
      title: "Everfall Forest Map",
      description: "config.internalLinks.maps-Everfall%20Forest.description",
      href: "/maps/Everfall%20Forest",
      iconName: "Map",
      bgImage: preview("everfall_forest"),
      linkText: "config.internalLinks.maps-Everfall%20Forest.linkText",
    },
    {
      title: "Duskdye Woods Map",
      description: "config.internalLinks.maps-Duskdye%20Woods.description",
      href: "/maps/Duskdye%20Woods",
      iconName: "Map",
      bgImage: preview("duskdye_woods"),
      linkText: "config.internalLinks.maps-Duskdye%20Woods.linkText",
    },
    {
      title: "Underground District Map",
      description:
        "config.internalLinks.maps-Underground%20District.description",
      href: "/maps/Underground%20District",
      iconName: "Map",
      bgImage: preview("underground_district"),
      linkText: "config.internalLinks.maps-Underground%20District.linkText",
    },
    {
      title: "Stray Starway Map",
      description: "config.internalLinks.maps-Stray%20Starway.description",
      href: "/maps/Stray%20Starway",
      iconName: "Map",
      bgImage: preview("stray_starway"),
      linkText: "config.internalLinks.maps-Stray%20Starway.linkText",
    },
    {
      title: "Skimmer's Lair Map",
      description: "config.internalLinks.maps-Skimmer's%20Lair.description",
      href: "/maps/Skimmer's%20Lair",
      iconName: "Map",
      bgImage: preview("skimmer_s_lair"),
      linkText: "config.internalLinks.maps-Skimmer's%20Lair.linkText",
    },
    {
      href: "/activities-tracker",
      title: "activities.navTitle",
      description: "activities.navDescription",
      linkText: "activities.navLinkText",
      iconName: "Activity",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: ["BPSR", "Bosses", "Guides", "Maps", "Rare Spawns", "Engram Hubs"],
  topFilters: ["monster_ignisor", "camera_point", "wind_barrier"],
  db: {
    // Collection checklists (/checklist, /checklist/<section>): the game's own
    // collections - reading material, the fishing log, Monster Hunt, Battle
    // Imagines and mounts.
    checklists: [
      { section: "reading-books" },
      { section: "fish" },
      { section: "monsters" },
      { section: "imagines" },
      { section: "mounts" },
    ],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "inventory",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/equipment",
        type: "equipment",
        titleKey: "equipment",
        titleFallback: "Gear",
        icon: "🛡️",
        description: "config.db.equipment.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "recipes",
        titleFallback: "Recipes",
        icon: "⚒️",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/imagines",
        type: "imagines",
        titleKey: "imagines",
        titleFallback: "Battle Imagine",
        icon: "✨",
        description: "config.db.imagines.description",
      },
      {
        href: "/db/monsters",
        type: "monsters",
        titleKey: "monsters",
        titleFallback: "Monster Hunt",
        icon: "👹",
        description: "config.db.monsters.description",
      },
      {
        href: "/db/dungeons",
        type: "dungeons",
        titleKey: "dungeons",
        titleFallback: "Dungeons",
        icon: "🏰",
        description: "config.db.dungeons.description",
      },
      {
        href: "/db/gathering",
        type: "gathering",
        titleKey: "gathering",
        titleFallback: "Gathering",
        icon: "🌿",
        description: "config.db.gathering.description",
      },
      {
        href: "/db/fish",
        type: "fish",
        titleKey: "fish",
        titleFallback: "Fish",
        icon: "🐟",
        description: "config.db.fish.description",
      },
      {
        href: "/db/mounts",
        type: "mounts",
        titleKey: "mounts",
        titleFallback: "Mounts",
        icon: "🐗",
        description: "config.db.mounts.description",
      },
      {
        href: "/db/furniture",
        type: "furniture",
        titleKey: "furniture",
        titleFallback: "Furniture",
        icon: "🪑",
        description: "config.db.furniture.description",
      },
      {
        href: "/db/shops",
        type: "shops",
        titleKey: "shops",
        titleFallback: "Shops",
        icon: "🏪",
        description: "config.db.shops.description",
      },
      {
        href: "/db/wardrobe",
        type: "wardrobe",
        titleKey: "wardrobe",
        titleFallback: "Wardrobe",
        icon: "👗",
        description: "config.db.wardrobe.description",
      },
      {
        href: "/db/weapon-skins",
        type: "weapon-skins",
        titleKey: "weapon-skins",
        titleFallback: "Weapon Skins",
        icon: "🗡️",
        description: "config.db.weapon-skins.description",
      },
      {
        href: "/db/emotes",
        type: "emotes",
        titleKey: "emotes",
        titleFallback: "Emotes",
        icon: "💃",
        description: "config.db.emotes.description",
      },
      {
        href: "/db/personalization",
        type: "personalization",
        titleKey: "personalization",
        titleFallback: "Personalization",
        icon: "🖼️",
        description: "config.db.personalization.description",
      },
      {
        href: "/db/titles",
        type: "titles",
        titleKey: "titles",
        titleFallback: "Titles",
        icon: "🏷️",
        description: "config.db.titles.description",
      },
      {
        href: "/db/dictionary",
        type: "dictionary",
        titleKey: "dictionary",
        icon: "📚",
        titleFallback: "Lore Dictionary",
        description: "config.db.dictionary.description",
      },
      {
        href: "/db/reading-books",
        type: "reading-books",
        titleKey: "reading-books",
        icon: "📖",
        titleFallback: "Reading Books",
        description: "config.db.reading-books.description",
      },
      {
        href: "/db/story",
        type: "story",
        titleKey: "story",
        icon: "✦",
        titleFallback: "Story Episodes",
        description: "config.db.story.description",
      },
    ],
    typeColors: {
      dictionary: "bg-cyan-900/40 text-cyan-400",
      "reading-books": "bg-amber-900/40 text-amber-400",
      story: "bg-indigo-900/40 text-indigo-400",
    },
    languageCount: 5,
  },
});
