import { resolveAppConfig } from "@repo/lib";

export const crimsonDesert = resolveAppConfig({
  name: "crimson-desert",
  supportedLocales: [
    "en",
    "ko",
    "ja",
    "fr",
    "de",
    "it",
    "pl",
    "pt-BR",
    "ru",
    "es",
    "tr",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  // Partner link (gaming.tools) — keep even with our own /db below.
  externalLinks: [
    {
      href: "https://crimsondesert.gaming.tools/",
      title: "database",
    },
  ],
  // No internalLinks: map cards are auto-generated from version.data.tiles
  // (Pywel + Abyss). Header "Maps" link now derives from hasMap in layout.
  keywords: [
    "Pywel",
    "Abyss Cresset",
    "Sealed Artifact",
    "Treasure Chest",
    "Stronghold",
    "Fast Travel",
    "Bonfire",
    "Mining",
    "Gathering",
    "Iron Ore",
    "Copper Ore",
    "Faction Quest",
    "Hernand",
    "Delesyia",
    "Demeniss",
  ],
  topFilters: [
    "abyss_gate",
    "treasure_box",
    "faction_quest",
    "memory_fragment",
    "bonfire",
    "camp",
    "mine_copper",
    "chest",
  ],
  // Database (codex): sections mirror data-forge `config/database.<type>.json`
  // (data-mining/src/crimson-desert/database.ts). Slugs avoid the static /db/<folder>
  // routes (items, weapons, creatures, …) and the map's filter-group keys.
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/equipment",
        type: "equipment",
        titleKey: "config.db.equipment.title",
        titleFallback: "Equipment",
        icon: "🗡️",
        description: "config.db.equipment.description",
      },
      {
        href: "/db/consumables",
        type: "consumables",
        titleKey: "config.db.consumables.title",
        titleFallback: "Consumables",
        icon: "🍲",
        description: "config.db.consumables.description",
      },
      {
        href: "/db/materials",
        type: "materials",
        titleKey: "config.db.materials.title",
        titleFallback: "Materials",
        icon: "🪨",
        description: "config.db.materials.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.db.recipes.title",
        titleFallback: "Recipes",
        icon: "🔨",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/vendors",
        type: "vendors",
        titleKey: "config.db.vendors.title",
        titleFallback: "Vendors",
        icon: "🏪",
        description: "config.db.vendors.description",
      },
      {
        href: "/db/bestiary",
        type: "bestiary",
        titleKey: "config.db.bestiary.title",
        titleFallback: "Bestiary",
        icon: "🐺",
        description: "config.db.bestiary.description",
      },
      {
        href: "/db/documents",
        type: "documents",
        titleKey: "config.db.documents.title",
        titleFallback: "Documents",
        icon: "📜",
        description: "config.db.documents.description",
      },
      {
        href: "/db/miscellaneous",
        type: "miscellaneous",
        titleKey: "config.db.miscellaneous.title",
        titleFallback: "Other Items",
        icon: "📦",
        description: "config.db.miscellaneous.description",
      },
    ],
    typeLabels: {
      equipment: "config.db.typeLabels.equipment",
      consumables: "config.db.typeLabels.consumables",
      materials: "config.db.typeLabels.materials",
      recipes: "config.db.typeLabels.recipes",
      vendors: "config.db.typeLabels.vendors",
      bestiary: "config.db.typeLabels.bestiary",
      documents: "config.db.typeLabels.documents",
      miscellaneous: "config.db.typeLabels.miscellaneous",
    },
  },
});
