import { resolveAppConfig } from "@repo/lib";

export const deltaForce = resolveAppConfig({
  name: "delta-force",
  // Marker names, container titles, extract names, region labels and the whole codex come
  // from the game's own locres exports in all 12 locales (data-forge dicts/*.json).
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "ja",
    "ko",
    "pt-BR",
    "ru",
    "th",
    "tr",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  internalLinks: [
    {
      title: "config.internalLinks.keycards.title",
      description: "config.internalLinks.keycards.description",
      href: "/db/keycards",
      iconName: "ShieldCheck",
      linkText: "config.internalLinks.keycards.linkText",
    },
    {
      title: "config.internalLinks.collectibles.title",
      description: "config.internalLinks.collectibles.description",
      href: "/db/collectibles",
      iconName: "Gift",
      linkText: "config.internalLinks.collectibles.linkText",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Extraction Points",
    "Keycard Rooms",
    "Safes",
    "Loot Containers",
    "Keycards",
    "Collectibles",
  ],
  topFilters: ["extract", "keycard_room", "c_safe", "c_small_safe", "boss"],
  db: {
    // Collection checklists (/checklist, /checklist/<section>).
    checklists: [{ section: "collectibles" }, { section: "keycards" }],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/keycards",
        type: "keycards",
        titleKey: "config.internalLinks.keycards.title",
        titleFallback: "Keycards",
        icon: "🔑",
        description: "config.db.keycards.description",
      },
      {
        href: "/db/collectibles",
        type: "collectibles",
        titleKey: "config.internalLinks.collectibles.title",
        titleFallback: "Collectibles",
        icon: "💎",
        description: "config.db.collectibles.description",
      },
      {
        href: "/db/gear",
        type: "gear",
        titleKey: "config.db.gear.title",
        titleFallback: "Gear",
        icon: "🪖",
        description: "config.db.gear.description",
      },
      {
        href: "/db/weapons",
        type: "weapons",
        titleKey: "config.db.weapons.title",
        titleFallback: "Weapons",
        icon: "🔫",
        description: "config.db.weapons.description",
      },
      {
        href: "/db/attachments",
        type: "attachments",
        titleKey: "config.db.attachments.title",
        titleFallback: "Attachments",
        icon: "🔧",
        description: "config.db.attachments.description",
      },
      {
        href: "/db/ammo",
        type: "ammo",
        titleKey: "config.db.ammo.title",
        titleFallback: "Ammo",
        icon: "🧨",
        description: "config.db.ammo.description",
      },
      {
        href: "/db/consumables",
        type: "consumables",
        titleKey: "config.db.consumables.title",
        titleFallback: "Consumables",
        icon: "💉",
        description: "config.db.consumables.description",
      },
      {
        href: "/db/operators",
        type: "operators",
        titleKey: "config.db.operators.title",
        titleFallback: "Operators",
        icon: "🎖️",
        description: "config.db.operators.description",
      },
    ],
    typeLabels: {
      keycards: "config.db.typeLabels.keycards",
      collectibles: "config.db.typeLabels.collectibles",
      gear: "config.db.typeLabels.gear",
      weapons: "config.db.typeLabels.weapons",
      attachments: "config.db.typeLabels.attachments",
      ammo: "config.db.typeLabels.ammo",
      consumables: "config.db.typeLabels.consumables",
      operators: "config.db.typeLabels.operators",
    },
  },
});
