import { resolveAppConfig, DATA_FORGE_CDN_URL } from "@repo/lib";

const preview = (mapId: string) =>
  `${DATA_FORGE_CDN_URL}/diablo4/map-tiles/${mapId}/preview.webp`;

export const diablo4 = resolveAppConfig({
  name: "diablo4",
  supportedLocales: [
    "en",
    "de",
    "es",
    "es-MX",
    "fr",
    "it",
    "ja",
    "ko",
    "pl",
    "pt-BR",
    "ru",
    "tr",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  withoutLiveMode: true,
  internalLinks: [
    {
      title: "Diablo IV Map",
      description: "config.internalLinks.maps-Sanctuary.description",
      href: "/maps/Sanctuary",
      iconName: "Map",
      linkText: "config.internalLinks.maps-Sanctuary.linkText",
      bgImage: preview("Sanctuary"),
    },
    {
      title: "config.internalLinks.aspects.title",
      description: "config.internalLinks.aspects.description",
      href: "/db/aspects",
      iconName: "BookOpen",
      linkText: "config.internalLinks.aspects.linkText",
    },
    {
      title: "config.internalLinks.uniques.title",
      description: "config.internalLinks.uniques.description",
      href: "/db/uniques",
      iconName: "Gift",
      linkText: "config.internalLinks.uniques.linkText",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
  ],
  externalLinks: [],
  keywords: ["Dungeons", "World Events", "Strongholds", "Nightmare Dungeons"],
  topFilters: [
    "altarsOfLilith",
    "tenetOfAkarat",
    "dungeons",
    "strongholds",
    "worldBossArenas",
    "waypoints",
    "cellars",
    "sideQuests",
  ],
  db: {
    // Collection checklists (/checklist, /checklist/<section>): the map's
    // collectibles, one codex entry per marker (data-forge diablo4 index.ts).
    checklists: [
      { section: "altars_of_lilith", descriptions: true },
      { section: "tenets_of_akarat", descriptions: true },
      { section: "chronicles_of_creation", descriptions: true },
      { section: "waypoints_list", descriptions: true },
      { section: "strongholds_list", descriptions: true },
      { section: "dungeons_list", descriptions: true },
    ],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "db_search_placeholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/aspects",
        type: "aspects",
        titleKey: "aspects",
        titleFallback: "Aspects",
        icon: "📖",
        description: "aspects_home_desc",
      },
      {
        href: "/db/uniques",
        type: "uniques",
        titleKey: "uniques",
        titleFallback: "Unique Items",
        icon: "💎",
        description: "uniques_home_desc",
      },
      {
        href: "/db/bosses",
        type: "bosses",
        titleKey: "bosses",
        titleFallback: "Boss Loot Tables",
        icon: "☠️",
        description: "bosses_home_desc",
      },
      {
        href: "/db/gems",
        type: "gems",
        titleKey: "gems",
        titleFallback: "Gems",
        icon: "💠",
        description: "gems_home_desc",
      },
      {
        href: "/db/runes",
        type: "runes",
        titleKey: "runes",
        titleFallback: "Runes",
        icon: "🔮",
        description: "runes_home_desc",
      },
      {
        href: "/db/glyphs",
        type: "glyphs",
        titleKey: "glyphs",
        titleFallback: "Paragon Glyphs",
        icon: "⭐",
        description: "glyphs_home_desc",
      },
      {
        href: "/db/temper_manuals",
        type: "temper_manuals",
        titleKey: "temper_manuals",
        titleFallback: "Temper Manuals",
        icon: "📜",
        description: "temper_manuals_home_desc",
      },
      {
        href: "/db/seals",
        type: "seals",
        titleKey: "seals",
        titleFallback: "Horadric Seals",
        icon: "🔰",
        description: "seals_home_desc",
      },
      // Collectibles — titles/labels are data-forge dict terms (game strings).
      {
        href: "/db/altars_of_lilith",
        type: "altars_of_lilith",
        titleKey: "altars_of_lilith",
        titleFallback: "Altars of Lilith",
        icon: "🗿",
        description: "altars_of_lilith_home_desc",
      },
      {
        href: "/db/tenets_of_akarat",
        type: "tenets_of_akarat",
        titleKey: "tenets_of_akarat",
        titleFallback: "Tenets of Akarat",
        icon: "📿",
        description: "tenets_of_akarat_home_desc",
      },
      {
        href: "/db/chronicles_of_creation",
        type: "chronicles_of_creation",
        titleKey: "chronicles_of_creation",
        titleFallback: "Chronicles of Creation",
        icon: "📘",
        description: "chronicles_of_creation_home_desc",
      },
      {
        href: "/db/waypoints_list",
        type: "waypoints_list",
        titleKey: "waypoints_list",
        titleFallback: "Waypoints",
        icon: "🌀",
        description: "waypoints_list_home_desc",
      },
      {
        href: "/db/strongholds_list",
        type: "strongholds_list",
        titleKey: "strongholds_list",
        titleFallback: "Strongholds",
        icon: "🏰",
        description: "strongholds_list_home_desc",
      },
      {
        href: "/db/dungeons_list",
        type: "dungeons_list",
        titleKey: "dungeons_list",
        titleFallback: "Dungeons",
        icon: "🕳️",
        description: "dungeons_list_home_desc",
      },
    ],
    typeLabels: {
      aspects: "aspects_one",
      uniques: "uniques_one",
      bosses: "bosses_one",
      gems: "gems_one",
      runes: "runes_one",
      glyphs: "glyphs_one",
      temper_manuals: "temper_manuals_one",
      seals: "seals_one",
      altars_of_lilith: "altars_of_lilith_one",
      tenets_of_akarat: "tenets_of_akarat_one",
      chronicles_of_creation: "chronicles_of_creation_one",
      waypoints_list: "waypoints_list_one",
      strongholds_list: "strongholds_list_one",
      dungeons_list: "dungeons_list_one",
    },
  },
});
