import { resolveAppConfig } from "@repo/lib";

export const dragonswordAwakening = resolveAppConfig({
  name: "dragonsword-awakening",
  // The game ships 11 languages in its server StringData catalog — real localized names
  // for every item/character/recipe (extracted from __GeneratedGameData__ XML).
  supportedLocales: [
    "en",
    "ja",
    "ko",
    "zh-CN",
    "zh-TW",
    "de",
    "fr",
    "es",
    "pt",
    "ru",
    "th",
  ],
  appUrl: "https://www.th.gl/companion-app",
  // No manual "/maps/Orbis" internalLink — the home page auto-generates a richer
  // map card (preview + live count), which a manual /maps link would shadow.
  internalLinks: [
    {
      title: "config.internalLinks.characters.title",
      description: "config.internalLinks.characters.description",
      href: "/db/characters",
      iconName: "Users",
      linkText: "config.internalLinks.characters.linkText",
    },
    {
      title: "config.internalLinks.recipes.title",
      description: "config.internalLinks.recipes.description",
      href: "/db/recipes",
      iconName: "BookOpen",
      linkText: "config.internalLinks.recipes.linkText",
    },
    {
      title: "config.internalLinks.mounts.title",
      description: "config.internalLinks.mounts.description",
      href: "/db/mounts",
      iconName: "Bug",
      linkText: "config.internalLinks.mounts.linkText",
    },
    {
      href: "/activities-tracker",
      title: "activities.navTitle",
      description: "activities.navDescription",
      linkText: "activities.navLinkText",
      iconName: "Activity",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Chests",
    "Cooking Ingredients",
    "Crafting Materials",
    "World Bosses",
    "Heroes",
    "Mounts",
    "Familiars",
  ],
  topFilters: [
    "chests_dig",
    "ingredients_carrot",
    "materials_reminiscecrystal",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "db.searchAll",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/characters",
        type: "characters",
        titleKey: "config.internalLinks.characters.title",
        titleFallback: "Characters",
        icon: "🦸",
        description: "config.db.characters.description",
      },
      {
        href: "/db/monsters",
        type: "monsters",
        titleKey: "config.db.monsters.title",
        titleFallback: "Bestiary",
        icon: "🐉",
        description: "config.db.monsters.description",
      },
      {
        href: "/db/npcs",
        type: "npcs",
        titleKey: "config.db.npcs.title",
        titleFallback: "NPCs",
        icon: "🗣️",
        description: "config.db.npcs.description",
      },
      {
        href: "/db/quests",
        type: "quests",
        titleKey: "config.db.quests.title",
        titleFallback: "Quests",
        icon: "📜",
        description: "config.db.quests.description",
      },
      {
        href: "/db/mounts",
        type: "mounts",
        titleKey: "config.internalLinks.mounts.title",
        titleFallback: "Mounts & Familiars",
        icon: "🐾",
        description: "config.db.mounts.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.internalLinks.recipes.title",
        titleFallback: "Cooking Recipes",
        icon: "🍳",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/ingredients_db",
        type: "ingredients_db",
        titleKey: "config.db.ingredients_db.title",
        titleFallback: "Ingredients",
        icon: "🥕",
        description: "config.db.ingredients_db.description",
      },
      {
        href: "/db/equipment",
        type: "equipment",
        titleKey: "config.db.equipment.title",
        titleFallback: "Equipment",
        icon: "🛡️",
        description: "config.db.equipment.description",
      },
      {
        href: "/db/materials_db",
        type: "materials_db",
        titleKey: "config.db.materials_db.title",
        titleFallback: "Materials",
        icon: "💎",
        description: "config.db.materials_db.description",
      },
      {
        href: "/db/costumes",
        type: "costumes",
        titleKey: "config.db.costumes.title",
        titleFallback: "Costumes",
        icon: "👗",
        description: "config.db.costumes.description",
      },
    ],
    typeLabels: {
      characters: "config.db.typeLabels.characters",
      monsters: "config.db.typeLabels.monsters",
      npcs: "config.db.typeLabels.npcs",
      quests: "config.db.typeLabels.quests",
      mounts: "config.db.typeLabels.mounts",
      recipes: "config.db.typeLabels.recipes",
      ingredients_db: "config.db.typeLabels.ingredients_db",
      equipment: "config.db.typeLabels.equipment",
      materials_db: "config.db.typeLabels.materials_db",
      costumes: "config.db.typeLabels.costumes",
    },
  },
});
