import { resolveAppConfig, DATA_FORGE_CDN_URL } from "@repo/lib";

// Inlined per-map preview URLs (avoid getPreviewImageUrl + cbor-x leak
// into middleware).
const preview = (mapId: string) =>
  `${DATA_FORGE_CDN_URL}/duet-night-abyss/map-tiles/${mapId}/preview.webp`;

// Locales = the six client languages (data-forge duet-night-abyss/localization.ts,
// TextMap_I18n).
export const duetNightAbyss = resolveAppConfig({
  name: "duet-night-abyss",
  supportedLocales: ["en", "fr", "ja", "ko", "zh-CN", "zh-TW"],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "Bloomfield Station Map",
      description: "config.internalLinks.maps-Bloomfield%20Station.description",
      href: "/maps/Bloomfield%20Station",
      iconName: "Map",
      bgImage: preview("Haiboliya_Chezhan_Main"),
      linkText: "config.internalLinks.maps-Bloomfield%20Station.linkText",
    },
    {
      title: "Ironworks Map",
      description: "config.internalLinks.maps-Ironworks.description",
      href: "/maps/Ironworks",
      iconName: "Map",
      bgImage: preview("Haiboliya_Chezhan_CZDX"),
      linkText: "config.internalLinks.maps-Ironworks.linkText",
    },
    {
      title: "Haojing Map",
      description: "config.internalLinks.maps-Haojing.description",
      href: "/maps/Haojing",
      iconName: "Map",
      bgImage: preview("Huaxu_Haojing_Main"),
      linkText: "config.internalLinks.maps-Haojing.linkText",
    },
    {
      title: "Mistwharf Map",
      description: "config.internalLinks.maps-Mistwharf.description",
      href: "/maps/Mistwharf",
      iconName: "Map",
      bgImage: preview("Huaxu_Yanjindu_Main"),
      linkText: "config.internalLinks.maps-Mistwharf.linkText",
    },
    {
      title: "Zhuyin Altar Map",
      description: "config.internalLinks.maps-Zhuyin%20Altar.description",
      href: "/maps/Zhuyin%20Altar",
      iconName: "Map",
      bgImage: preview("Huaxu_Yanjindu_Alt"),
      linkText: "config.internalLinks.maps-Zhuyin%20Altar.linkText",
    },
    {
      title: "Purgatorio Island Map",
      description: "config.internalLinks.maps-Purgatorio%20Island.description",
      href: "/maps/Purgatorio%20Island",
      iconName: "Map",
      bgImage: preview("Prologue"),
      linkText: "config.internalLinks.maps-Purgatorio%20Island.linkText",
    },
    {
      title: "Lonza Fortress Map",
      description: "config.internalLinks.maps-Lonza%20Fortress.description",
      href: "/maps/Lonza%20Fortress",
      iconName: "Map",
      bgImage: preview("EX01"),
      linkText: "config.internalLinks.maps-Lonza%20Fortress.linkText",
    },
    {
      title: "Eastern District, Icelake Map",
      description:
        "config.internalLinks.maps-Eastern%20District%2C%20Icelake.description",
      href: "/maps/Eastern%20District%2C%20Icelake",
      iconName: "Map",
      bgImage: preview("Chapter01"),
      linkText:
        "config.internalLinks.maps-Eastern%20District%2C%20Icelake.linkText",
    },
    {
      title: "Glevum Pit Map",
      description: "config.internalLinks.maps-Glevum%20Pit.description",
      href: "/maps/Glevum%20Pit",
      iconName: "Map",
      bgImage: preview("Chapter01_KK"),
      linkText: "config.internalLinks.maps-Glevum%20Pit.linkText",
    },
    {
      title: "Icelake Sewers Map",
      description: "config.internalLinks.maps-Icelake%20Sewers.description",
      href: "/maps/Icelake%20Sewers",
      iconName: "Map",
      bgImage: preview("Chapter01_Sew"),
      linkText: "config.internalLinks.maps-Icelake%20Sewers.linkText",
    },
    {
      title: "Galea Theatre Map",
      description: "config.internalLinks.maps-Galea%20Theatre.description",
      href: "/maps/Galea%20Theatre",
      iconName: "Map",
      bgImage: preview("Chapter01_Thea"),
      linkText: "config.internalLinks.maps-Galea%20Theatre.linkText",
    },
    {
      href: "/activities-tracker",
      title: "activities.navTitle",
      description: "activities.navDescription",
      linkText: "activities.navLinkText",
      iconName: "Activity",
    },
    {
      href: "/db/quests",
      title: "config.internalLinks.quests.title",
      linkText: "config.internalLinks.quests.linkText",
      iconName: "BookOpen",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: ["DNA", "Geniemon", "Chests", "Collectibles", "Readables"],
  topFilters: ["geniemon_zisha"],
  db: {
    // Collection checklists: the map's collectibles and the game's own
    // collection logs (fish, Geniemon, achievements).
    checklists: [
      { section: "readables" },
      { section: "music" },
      { section: "fish" },
      { section: "geniemons", descriptions: false },
      { section: "achievements", descriptions: true },
    ],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/characters",
        type: "characters",
        titleKey: "characters",
        titleFallback: "Characters",
        icon: "🧑",
        description: "config.db.characters.description",
      },
      {
        href: "/db/weaponry",
        type: "weaponry",
        titleKey: "weaponry",
        titleFallback: "Weapons",
        icon: "⚔️",
        description: "config.db.weaponry.description",
      },
      {
        href: "/db/demon_wedges",
        type: "demon_wedges",
        titleKey: "demon_wedges",
        titleFallback: "Demon Wedges",
        icon: "🔷",
        description: "config.db.demon_wedges.description",
      },
      {
        href: "/db/geniemons",
        type: "geniemons",
        titleKey: "geniemons",
        titleFallback: "Geniemon",
        icon: "🐾",
        description: "config.db.geniemons.description",
      },
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "inventory",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/forging",
        type: "forging",
        titleKey: "forging",
        titleFallback: "Forging",
        icon: "🔨",
        description: "config.db.forging.description",
      },
      {
        href: "/db/enemies",
        type: "enemies",
        titleKey: "enemies",
        titleFallback: "Enemies",
        icon: "👹",
        description: "config.db.enemies.description",
      },
      {
        href: "/db/fish",
        type: "fish",
        titleKey: "fish",
        titleFallback: "Fish",
        icon: "🐟",
        description: "config.db.fish.description",
      },
      {
        href: "/db/readables",
        type: "readables",
        titleKey: "readables",
        titleFallback: "Reading",
        icon: "📖",
        description: "config.db.readables.description",
      },
      {
        href: "/db/music",
        type: "music",
        titleKey: "music",
        titleFallback: "Sheet Music",
        icon: "🎼",
        description: "config.db.music.description",
      },
      {
        href: "/db/accessories",
        type: "accessories",
        titleKey: "accessories",
        titleFallback: "Accessories",
        icon: "🎀",
        description: "config.db.accessories.description",
      },
      {
        href: "/db/encyclopedia",
        type: "encyclopedia",
        titleKey: "encyclopedia",
        titleFallback: "Encyclopedia",
        icon: "📚",
        description: "config.db.encyclopedia.description",
      },
      {
        href: "/db/achievements",
        type: "achievements",
        titleKey: "achievements",
        titleFallback: "Achievements",
        icon: "🏆",
        description: "config.db.achievements.description",
      },
      {
        href: "/db/quests",
        // Quests live across one exact category (`mainquests`) plus three
        // `sidequests_*` subcategories — match the umbrella via prefix
        // and include `mainquests` explicitly.
        type: "mainquests",
        extraTypes: [
          "sidequests_character",
          "sidequests_story",
          "sidequests_world",
        ],
        icon: "📜",
        titleKey: "config.db.mainquests.title",
        titleFallback: "Quests",
        description: "config.db.mainquests.description",
      },
    ],
    typeLabels: {
      characters: "config.db.typeLabels.characters",
      weaponry: "config.db.typeLabels.weaponry",
      demon_wedges: "config.db.typeLabels.demon_wedges",
      geniemons: "config.db.typeLabels.geniemons",
      inventory: "config.db.typeLabels.inventory",
      forging: "config.db.typeLabels.forging",
      enemies: "config.db.typeLabels.enemies",
      fish: "config.db.typeLabels.fish",
      readables: "config.db.typeLabels.readables",
      music: "config.db.typeLabels.music",
      accessories: "config.db.typeLabels.accessories",
      encyclopedia: "config.db.typeLabels.encyclopedia",
      achievements: "config.db.typeLabels.achievements",
      mainquests: "config.db.typeLabels.mainquests",
      sidequests_character: "config.db.typeLabels.sidequests_character",
      sidequests_story: "config.db.typeLabels.sidequests_story",
      sidequests_world: "config.db.typeLabels.sidequests_world",
    },
    typeColors: {
      mainquests: "bg-amber-900/40 text-amber-400",
      sidequests_character: "bg-blue-900/40 text-blue-400",
      sidequests_story: "bg-purple-900/40 text-purple-400",
      sidequests_world: "bg-emerald-900/40 text-emerald-400",
    },
  },
});
