import { resolveAppConfig, DATA_FORGE_CDN_URL } from "@repo/lib";

export const gothic1Remake = resolveAppConfig({
  name: "gothic-1-remake",
  supportedLocales: [
    "en",
    "de",
    "fr",
    "es",
    "it",
    "pt-BR",
    "ru",
    "pl",
    "ja",
    "zh-CN",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "Khorinis Map",
      description: "config.internalLinks.maps-Khorinis.description",
      href: "/maps/Khorinis",
      iconName: "Map",
      bgImage: `${DATA_FORGE_CDN_URL}/gothic-1-remake/map-tiles/Khorinis/preview.webp?v=1`,
      linkText: "config.internalLinks.maps-Khorinis.linkText",
    },
    {
      href: "/db/item",
      title: "config.internalLinks.item.title",
      linkText: "config.internalLinks.item.linkText",
      iconName: "Gift",
      description: "config.internalLinks.item.description",
    },
    {
      href: "/db/creature",
      title: "config.internalLinks.creature.title",
      linkText: "config.internalLinks.creature.linkText",
      iconName: "Bug",
      description: "config.internalLinks.creature.description",
    },
    {
      href: "/db/trader",
      title: "config.internalLinks.trader.title",
      linkText: "config.internalLinks.trader.linkText",
      iconName: "Handshake",
      description: "config.internalLinks.trader.description",
    },
    {
      href: "/db/quest",
      title: "config.internalLinks.quest.title",
      linkText: "config.internalLinks.quest.linkText",
      iconName: "ScrollText",
      description: "config.internalLinks.quest.description",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Gothic",
    "Gothic 1 Remake",
    "Khorinis",
    "The Colony",
    "Chests",
    "Focus Stones",
    "Ore",
    "Items",
  ],
  topFilters: ["chest", "fishing_spot", "focus_stone", "ore_vein"],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    // Every section below also becomes a header-nav item (de-duped against
    // internalLinks, overflowing into "More") — so materials/misc/runes/etc.
    // are reachable from the nav without hand-listing each in internalLinks.
    sectionsInNav: true,
    // Consolidated nav: all item categories live under one "Items" section
    // (aggregated via extraTypes; the page still sub-groups by weapon/armor/…),
    // plus Bestiary, Traders and Quests. Old per-category URLs redirect to
    // /db/items (see next.config redirects).
    homeSections: [
      {
        href: "/db/item",
        type: "item",
        icon: "🎒",
        extraTypes: [
          "weapon",
          "armor",
          "potion",
          "herb",
          "food",
          "rune",
          "scroll",
          "amulet",
          "ring",
          "material",
          "key",
          "misc",
          "writing",
        ],
      },
      { href: "/db/creature", type: "creature", icon: "🐾" },
      { href: "/db/trader", type: "trader", icon: "🪙" },
      { href: "/db/quest", type: "quest", icon: "📜" },
    ],
    homeExtraLinks: [],
    typeLabels: {
      item: "config.db.typeLabels.item",
      quest: "config.db.typeLabels.quest",
      weapon: "config.db.typeLabels.weapon",
      armor: "config.db.typeLabels.armor",
      potion: "config.db.typeLabels.potion",
      herb: "config.db.typeLabels.herb",
      food: "config.db.typeLabels.food",
      rune: "config.db.typeLabels.rune",
      scroll: "config.db.typeLabels.scroll",
      amulet: "config.db.typeLabels.amulet",
      ring: "config.db.typeLabels.ring",
      material: "config.db.typeLabels.material",
      key: "config.db.typeLabels.key",
      writing: "config.db.typeLabels.writing",
      misc: "config.db.typeLabels.misc",
      fishing: "config.db.typeLabels.fishing",
      trader: "config.db.typeLabels.trader",
      creature: "config.db.typeLabels.creature",
    },
    typeColors: {
      item: "bg-amber-900/40 text-amber-400",
      quest: "bg-purple-900/40 text-purple-400",
      weapon: "bg-red-900/40 text-red-400",
      armor: "bg-slate-700/40 text-slate-300",
      potion: "bg-emerald-900/40 text-emerald-400",
      herb: "bg-green-900/40 text-green-400",
      food: "bg-orange-900/40 text-orange-400",
      rune: "bg-purple-900/40 text-purple-400",
      scroll: "bg-amber-900/40 text-amber-400",
      amulet: "bg-cyan-900/40 text-cyan-400",
      ring: "bg-yellow-900/40 text-yellow-400",
      material: "bg-stone-700/40 text-stone-300",
      key: "bg-yellow-900/40 text-yellow-400",
      writing: "bg-sky-900/40 text-sky-400",
      misc: "bg-neutral-700/40 text-neutral-300",
      fishing: "bg-blue-900/40 text-blue-400",
      trader: "bg-amber-900/40 text-amber-400",
      creature: "bg-rose-900/40 text-rose-400",
    },
    languageCount: 10,
  },
});
