import { resolveAppConfig } from "@repo/lib";

export const graveyardKeeper2 = resolveAppConfig({
  name: "graveyard-keeper-2",
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "ja",
    "ko",
    "pl",
    "pt-BR",
    "ru",
    "tr",
    "zh-CN",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Milestones",
    "Battles",
    "Iron Ore",
    "Marble",
    "Fishing Spots",
    "Town Restoration",
    "Tech Tree",
    "Recipes",
    "Traders",
  ],
  topFilters: [
    "fast_travel",
    "battle",
    "iron_ore_node",
    "fishing",
    "restoration",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/items",
        type: "items",
        titleKey: "config.db.items.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.items.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.db.recipes.title",
        titleFallback: "Recipes",
        icon: "🔨",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/techs",
        type: "techs",
        titleKey: "config.db.techs.title",
        titleFallback: "Tech Tree",
        icon: "📜",
        description: "config.db.techs.description",
      },
      {
        href: "/db/buildings",
        type: "buildings",
        titleKey: "config.db.buildings.title",
        titleFallback: "Buildings",
        icon: "🏗️",
        description: "config.db.buildings.description",
      },
      {
        href: "/db/skills",
        type: "skills",
        titleKey: "config.db.skills.title",
        titleFallback: "Masteries",
        icon: "⭐",
        description: "config.db.skills.description",
      },
      {
        href: "/db/perks",
        type: "perks",
        titleKey: "config.db.perks.title",
        titleFallback: "Perks",
        icon: "🧟",
        description: "config.db.perks.description",
      },
      {
        href: "/db/traders",
        type: "traders",
        titleKey: "config.db.traders.title",
        titleFallback: "Traders",
        icon: "💰",
        description: "config.db.traders.description",
      },
      {
        href: "/db/quests",
        type: "quests",
        titleKey: "config.db.quests.title",
        titleFallback: "Quests",
        icon: "❗",
        description: "config.db.quests.description",
      },
      {
        href: "/db/battles",
        type: "battles",
        titleKey: "config.db.battles.title",
        titleFallback: "Battles",
        icon: "⚔️",
        description: "config.db.battles.description",
      },
      {
        href: "/db/alchemy",
        type: "alchemy",
        titleKey: "config.db.alchemy.title",
        titleFallback: "Alchemy",
        icon: "⚗️",
        description: "config.db.alchemy.description",
      },
      {
        href: "/db/sermons",
        type: "sermons",
        titleKey: "config.db.sermons.title",
        titleFallback: "Sermons",
        icon: "⛪",
        description: "config.db.sermons.description",
      },
      {
        href: "/db/inspirations",
        type: "inspirations",
        titleKey: "config.db.inspirations.title",
        titleFallback: "Inspirations",
        icon: "💡",
        description: "config.db.inspirations.description",
      },
      {
        href: "/db/achievements",
        type: "achievements",
        titleKey: "config.db.achievements.title",
        titleFallback: "Achievements",
        icon: "🏆",
        description: "config.db.achievements.description",
      },
      {
        href: "/db/town-buildings",
        type: "town-buildings",
        titleKey: "config.db.town-buildings.title",
        titleFallback: "Town Buildings",
        icon: "🏘️",
        description: "config.db.town-buildings.description",
      },
      {
        href: "/db/ingredient-groups",
        type: "ingredient-groups",
        titleKey: "config.db.ingredient-groups.title",
        titleFallback: "Ingredient Groups",
        icon: "🧺",
        description: "config.db.ingredient-groups.description",
      },
    ],
    typeLabels: {
      items: "config.db.typeLabels.items",
      recipes: "config.db.typeLabels.recipes",
      techs: "config.db.typeLabels.techs",
      buildings: "config.db.typeLabels.buildings",
      skills: "config.db.typeLabels.skills",
      traders: "config.db.typeLabels.traders",
      quests: "config.db.typeLabels.quests",
      battles: "config.db.typeLabels.battles",
      alchemy: "config.db.typeLabels.alchemy",
      sermons: "config.db.typeLabels.sermons",
      inspirations: "config.db.typeLabels.inspirations",
      achievements: "config.db.typeLabels.achievements",
      perks: "config.db.typeLabels.perks",
      "town-buildings": "config.db.typeLabels.town-buildings",
      "ingredient-groups": "config.db.typeLabels.ingredient-groups",
    },
  },
});
