import { resolveAppConfig } from "@repo/lib";

export const grounded2 = resolveAppConfig({
  name: "grounded2",
  supportedLocales: [
    "en",
    "de",
    "es",
    "es-MX",
    "fr",
    "it",
    "ja",
    "ko",
    "pt-BR",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  // Map cards (Brookhollow Park + The Abyss) are auto-generated from the map
  // list — no manual internalLinks map entries (they'd shadow the richer cards).
  internalLinks: [
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
    {
      title: "weak.navTitle",
      description: "weak.navDescription",
      href: "/weakness-chart",
      iconName: "Bug",
      linkText: "weak.navLinkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: ["Wonders", "Ominent Facilities", "Resources"],
  db: {
    // Collection checklists (/checklist, /checklist/<section>).
    checklists: [{ section: "creatures" }, { section: "trinkets" }],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/weapons",
        type: "weapons",
        titleKey: "config.db.weapons.title",
        titleFallback: "Weapons & Tools",
        icon: "🗡️",
        description: "config.db.weapons.description",
      },
      {
        href: "/db/armor",
        type: "armor",
        titleKey: "config.db.armor.title",
        titleFallback: "Armor",
        icon: "🛡️",
        description: "config.db.armor.description",
      },
      {
        href: "/db/creatures",
        type: "creatures",
        titleKey: "config.db.creatures.title",
        titleFallback: "Creatures",
        icon: "🐛",
        description: "config.db.creatures.description",
      },
      {
        href: "/db/materials",
        type: "materials",
        titleKey: "config.db.materials.title",
        titleFallback: "Materials",
        icon: "🪨",
        description: "config.db.materials.description",
      },
      {
        href: "/db/consumables",
        type: "consumables",
        titleKey: "config.db.consumables.title",
        titleFallback: "Consumables",
        icon: "🍖",
        description: "config.db.consumables.description",
      },
      {
        href: "/db/trinkets",
        type: "trinkets",
        titleKey: "config.db.trinkets.title",
        titleFallback: "Trinkets",
        icon: "📿",
        description: "config.db.trinkets.description",
      },
      {
        href: "/db/ammo",
        type: "ammo",
        titleKey: "config.db.ammo.title",
        titleFallback: "Ammo & Throwables",
        icon: "🏹",
        description: "config.db.ammo.description",
      },
      {
        href: "/db/buildings",
        type: "buildings",
        titleKey: "config.db.buildings.title",
        titleFallback: "Buildings",
        icon: "🏠",
        description: "config.db.buildings.description",
      },
      {
        href: "/db/buggies",
        type: "buggies",
        titleKey: "config.db.buggies.title",
        titleFallback: "Buggies",
        icon: "🏎️",
        description: "config.db.buggies.description",
      },
      {
        href: "/db/key-items",
        type: "key-items",
        titleKey: "config.db.key-items.title",
        titleFallback: "Key Items",
        icon: "🗝️",
        description: "config.db.key-items.description",
      },
      {
        href: "/db/alternate-recipes",
        type: "alternate-recipes",
        titleKey: "config.db.alternate-recipes.title",
        titleFallback: "Alternate Recipes",
        icon: "🔀",
        description: "config.db.alternate-recipes.description",
      },
      {
        href: "/db/damage-types",
        type: "damage-types",
        titleKey: "config.db.damage-types.title",
        titleFallback: "Damage Types",
        icon: "💥",
        description: "config.db.damage-types.description",
      },
    ],
    typeLabels: {
      weapons: "config.db.typeLabels.weapons",
      armor: "config.db.typeLabels.armor",
      creatures: "config.db.typeLabels.creatures",
      materials: "config.db.typeLabels.materials",
      consumables: "config.db.typeLabels.consumables",
      trinkets: "config.db.typeLabels.trinkets",
      ammo: "config.db.typeLabels.ammo",
      buildings: "config.db.typeLabels.buildings",
      buggies: "config.db.typeLabels.buggies",
      "key-items": "config.db.typeLabels.key-items",
      "alternate-recipes": "config.db.typeLabels.alternate-recipes",
      "damage-types": "config.db.typeLabels.damage-types",
    },
  },
});
