import { resolveAppConfig } from "@repo/lib";

/**
 * Heartopia — database-only codex for XD Inc's life-sim. World positions are
 * runtime/zone-spawned, so there is no interactive map; the value is the
 * multi-locale codex (fish, insects, birds, recipes, wildlife, NPCs, …),
 * rendered through the generic `/db/[section]` + `/db/[section]/[id]` routes.
 *
 * Section slugs match the generated `database.<type>.json` types and don't
 * collide with HoMM Olden Era's static `/db/units`, … route folders.
 */
export const heartopia = resolveAppConfig({
  name: "heartopia",
  supportedLocales: [
    "en",
    "zh-CN",
    "zh-TW",
    "de",
    "fr",
    "ja",
    "ko",
    "es",
    "pt",
    "th",
    "ru",
    "id",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      href: "/db/fish",
      title: "Fish",
      linkText: "Browse fish",
      iconName: "Fish",
      description: "Every catchable fish, its habitat, value and trivia.",
    },
    {
      href: "/db/insects",
      title: "Insects",
      linkText: "Browse insects",
      iconName: "Bug",
      description: "Butterflies, beetles and more, with science facts.",
    },
    {
      href: "/db/birds",
      title: "Birds",
      linkText: "Browse birds",
      iconName: "Bird",
      description: "Photographable birds and their info cards.",
    },
    {
      href: "/db/recipes",
      title: "Recipes",
      linkText: "Browse recipes",
      iconName: "ChefHat",
      description: "Cooking and crafting recipes.",
    },
    {
      href: "/db/flowers",
      title: "Flowers",
      linkText: "Browse flowers",
      iconName: "Flower",
      description: "Flowers and garden plants.",
    },
    {
      href: "/db/animals",
      title: "Wildlife",
      linkText: "Browse wildlife",
      iconName: "PawPrint",
      description: "Wild animals you can meet around town.",
    },
    {
      href: "/db/npcs",
      title: "NPCs",
      linkText: "Browse NPCs",
      iconName: "Users",
      description: "Town residents and their profiles.",
    },
    {
      href: "/db/locations",
      title: "Locations",
      linkText: "Browse locations",
      iconName: "MapPin",
      description: "Stores, services and points of interest.",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Heartopia",
    "Database",
    "Codex",
    "Fish",
    "Insects",
    "Birds",
    "Recipes",
    "NPCs",
    "Wildlife",
  ],
  db: {
    heroSubtitle: "Game Database",
    searchPlaceholder: "Search fish, insects, recipes...",
    homeSections: [
      { href: "/db/fish", type: "fish", titleFallback: "Fish", icon: "🐟" },
      {
        href: "/db/insects",
        type: "insects",
        titleFallback: "Insects",
        icon: "🦋",
      },
      { href: "/db/birds", type: "birds", titleFallback: "Birds", icon: "🐦" },
      {
        href: "/db/recipes",
        type: "recipes",
        titleFallback: "Recipes",
        icon: "🍳",
      },
      {
        href: "/db/flowers",
        type: "flowers",
        titleFallback: "Flowers",
        icon: "🌸",
      },
      {
        href: "/db/food_materials",
        type: "food_materials",
        titleFallback: "Ingredients",
        icon: "🥕",
      },
      {
        href: "/db/animals",
        type: "animals",
        titleFallback: "Wildlife",
        icon: "🐾",
      },
      { href: "/db/dogs", type: "dogs", titleFallback: "Dogs", icon: "🐕" },
      { href: "/db/cats", type: "cats", titleFallback: "Cats", icon: "🐈" },
      { href: "/db/npcs", type: "npcs", titleFallback: "NPCs", icon: "🧑" },
      {
        href: "/db/locations",
        type: "locations",
        titleFallback: "Locations",
        icon: "📍",
      },
    ],
    typeLabels: {
      fish: "Fish",
      insects: "Insect",
      birds: "Bird",
      recipes: "Recipe",
      flowers: "Flower",
      food_materials: "Ingredient",
      animals: "Animal",
      dogs: "Dog",
      cats: "Cat",
      npcs: "NPC",
      locations: "Location",
    },
    typeColors: {
      fish: "bg-sky-900/40 text-sky-400",
      insects: "bg-lime-900/40 text-lime-400",
      birds: "bg-cyan-900/40 text-cyan-400",
      recipes: "bg-orange-900/40 text-orange-400",
      flowers: "bg-pink-900/40 text-pink-400",
      food_materials: "bg-amber-900/40 text-amber-400",
      animals: "bg-emerald-900/40 text-emerald-400",
      dogs: "bg-yellow-900/40 text-yellow-400",
      cats: "bg-purple-900/40 text-purple-400",
      npcs: "bg-rose-900/40 text-rose-400",
      locations: "bg-teal-900/40 text-teal-400",
    },
    languageCount: 12,
  },
});
