import { resolveAppConfig } from "@repo/lib";

/**
 * Heartopia — database-only codex for XD Inc's life-sim. World positions are
 * runtime/zone-spawned, so there is no interactive map; the value is the
 * multi-locale codex (fish, insects, birds, recipes, wildlife, NPCs, …),
 * rendered through the generic `/db/[section]` + `/db/[section]/[id]` routes.
 *
 * Section slugs match the generated `database.<type>.json` types and don't
 * collide with HoMM Olden Era's static `/db/units`, … route folders.
 */
export const heartopia = resolveAppConfig({
  name: "heartopia",
  supportedLocales: [
    "en",
    "zh-CN",
    "zh-TW",
    "de",
    "fr",
    "ja",
    "ko",
    "es",
    "pt",
    "th",
    "ru",
    "id",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      href: "/forecast",
      bgImage: "/games/thgl-web/tools/forecast.webp",
      title: "config.internalLinks.forecast.title",
      linkText: "config.internalLinks.forecast.linkText",
      iconName: "CloudSun",
      description: "config.internalLinks.forecast.description",
    },
    {
      href: "/db/fish",
      title: "config.internalLinks.fish.title",
      linkText: "config.internalLinks.fish.linkText",
      iconName: "Fish",
      description: "config.internalLinks.fish.description",
    },
    {
      href: "/db/insects",
      title: "config.internalLinks.insects.title",
      linkText: "config.internalLinks.insects.linkText",
      iconName: "Bug",
      description: "config.internalLinks.insects.description",
    },
    {
      href: "/db/birds",
      title: "config.internalLinks.birds.title",
      linkText: "config.internalLinks.birds.linkText",
      iconName: "Bird",
      description: "config.internalLinks.birds.description",
    },
    {
      href: "/db/recipes",
      title: "config.internalLinks.recipes.title",
      linkText: "config.internalLinks.recipes.linkText",
      iconName: "ChefHat",
      description: "config.internalLinks.recipes.description",
    },
    {
      href: "/db/flowers",
      title: "config.internalLinks.flowers.title",
      linkText: "config.internalLinks.flowers.linkText",
      iconName: "Flower",
      description: "config.internalLinks.flowers.description",
    },
    {
      href: "/db/animals",
      title: "config.internalLinks.animals.title",
      linkText: "config.internalLinks.animals.linkText",
      iconName: "PawPrint",
      description: "config.internalLinks.animals.description",
    },
    {
      href: "/db/npcs",
      title: "config.internalLinks.npcs.title",
      linkText: "config.internalLinks.npcs.linkText",
      iconName: "Users",
      description: "config.internalLinks.npcs.description",
    },
    {
      href: "/db/locations",
      title: "config.internalLinks.locations.title",
      linkText: "config.internalLinks.locations.linkText",
      iconName: "MapPin",
      description: "config.internalLinks.locations.description",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
    {
      href: "/activities-tracker",
      title: "activities.navTitle",
      description: "activities.navDescription",
      linkText: "activities.navLinkText",
      iconName: "Activity",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Heartopia",
    "Database",
    "Codex",
    "Fish",
    "Insects",
    "Birds",
    "Recipes",
    "Cooking",
    "NPCs",
    "Wildlife",
  ],
  db: {
    // Collection checklists (/checklist, /checklist/<section>).
    checklists: [
      { section: "fish" },
      { section: "insects" },
      { section: "birds" },
      { section: "flowers" },
    ],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    homeSections: [
      {
        href: "/db/fish",
        type: "fish",
        titleKey: "config.internalLinks.fish.title",
        titleFallback: "Fish",
        icon: "🐟",
      },
      {
        href: "/db/insects",
        type: "insects",
        titleKey: "config.internalLinks.insects.title",
        titleFallback: "Insects",
        icon: "🦋",
      },
      {
        href: "/db/birds",
        type: "birds",
        titleKey: "config.internalLinks.birds.title",
        titleFallback: "Birds",
        icon: "🐦",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.internalLinks.recipes.title",
        titleFallback: "Recipes",
        icon: "🔨",
      },
      {
        href: "/db/cooking",
        type: "cooking",
        titleKey: "config.db.cooking.title",
        titleFallback: "Cooking",
        icon: "🍳",
      },
      {
        href: "/db/materials",
        type: "materials",
        titleKey: "config.db.materials.title",
        titleFallback: "Materials",
        icon: "🪵",
      },
      {
        href: "/db/flowers",
        type: "flowers",
        titleKey: "config.internalLinks.flowers.title",
        titleFallback: "Flowers",
        icon: "🌸",
      },
      {
        href: "/db/food_materials",
        type: "food_materials",
        titleKey: "config.db.food_materials.title",
        titleFallback: "Ingredients",
        icon: "🥕",
      },
      {
        href: "/db/animals",
        type: "animals",
        titleKey: "config.internalLinks.animals.title",
        titleFallback: "Wildlife",
        icon: "🐾",
      },
      {
        href: "/db/dogs",
        type: "dogs",
        titleKey: "config.db.dogs.title",
        titleFallback: "Dogs",
        icon: "🐕",
      },
      {
        href: "/db/cats",
        type: "cats",
        titleKey: "config.db.cats.title",
        titleFallback: "Cats",
        icon: "🐈",
      },
      {
        href: "/db/npcs",
        type: "npcs",
        titleKey: "config.internalLinks.npcs.title",
        titleFallback: "NPCs",
        icon: "🧑",
      },
      {
        href: "/db/locations",
        type: "locations",
        titleKey: "config.internalLinks.locations.title",
        titleFallback: "Locations",
        icon: "📍",
      },
    ],
    typeLabels: {
      fish: "config.db.typeLabels.fish",
      insects: "config.db.typeLabels.insects",
      birds: "config.db.typeLabels.birds",
      recipes: "config.db.typeLabels.recipes",
      cooking: "config.db.typeLabels.cooking",
      materials: "config.db.typeLabels.materials",
      flowers: "config.db.typeLabels.flowers",
      food_materials: "config.db.typeLabels.food_materials",
      animals: "config.db.typeLabels.animals",
      dogs: "config.db.typeLabels.dogs",
      cats: "config.db.typeLabels.cats",
      npcs: "config.db.typeLabels.npcs",
      locations: "config.db.typeLabels.locations",
    },
    typeColors: {
      fish: "bg-sky-900/40 text-sky-400",
      insects: "bg-lime-900/40 text-lime-400",
      birds: "bg-cyan-900/40 text-cyan-400",
      recipes: "bg-orange-900/40 text-orange-400",
      cooking: "bg-red-900/40 text-red-400",
      materials: "bg-stone-800/40 text-stone-300",
      flowers: "bg-pink-900/40 text-pink-400",
      food_materials: "bg-amber-900/40 text-amber-400",
      animals: "bg-emerald-900/40 text-emerald-400",
      dogs: "bg-yellow-900/40 text-yellow-400",
      cats: "bg-purple-900/40 text-purple-400",
      npcs: "bg-rose-900/40 text-rose-400",
      locations: "bg-teal-900/40 text-teal-400",
    },
    languageCount: 12,
  },
});
