import { type AppConfig } from "@repo/lib";

// Maps are NOT listed here: the home page auto-generates a card per map in
// version.data.tiles. Locales = the languages the client ships (data-forge
// hogwarts-legacy/localization.ts; Arabic is not mined yet).
export const hogwartsLegacy: AppConfig = {
  name: "hogwarts-legacy",
  title: "Hogwarts Legacy",
  domain: "hogwarts",
  supportedLocales: [
    "en",
    "de",
    "es",
    "es-MX",
    "fr",
    "it",
    "ja",
    "ko",
    "pl",
    "pt-BR",
    "ru",
    "zh-CN",
    "zh-TW",
  ],
  // The Hogwarts Legacy Overwolf app was deprecated; the game is now supported
  // via the THGL Companion App (same as Avowed). The old Overwolf URL 404s.
  appUrl: "https://www.th.gl/companion-app",
  markerOptions: {
    radius: 6,
    playerIcon: "player.webp",
    imageSprite: true,
    zPos: {
      xyMaxDistance: 15000,
      zDistance: 350,
    },
  },
  internalLinks: [
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  keywords: ["Accio Page", "Field Guide Pages", "Collections"],
  db: {
    // Collection checklists: the Field Guide's Collections and the map's
    // collectibles (one codex entry per marker).
    checklists: [
      { section: "field_guide" },
      { section: "merlin_trials" },
      { section: "demiguise_statues" },
      { section: "astronomy_tables" },
      { section: "ancient_magic_hotspots" },
      { section: "treasure_vaults" },
      { section: "balloon_challenges" },
      { section: "landing_platforms" },
      { section: "beasts" },
      { section: "enemies" },
      { section: "brooms" },
      { section: "wand_handles" },
      { section: "traits" },
      { section: "conjurations" },
      { section: "challenges", descriptions: true },
    ],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/spells",
        type: "spells",
        titleKey: "spells",
        titleFallback: "Spells",
        icon: "🪄",
        description: "config.db.spells.description",
      },
      {
        href: "/db/talents",
        type: "talents",
        titleKey: "talents",
        titleFallback: "Talents",
        icon: "⭐",
        description: "config.db.talents.description",
      },
      {
        href: "/db/gear",
        type: "gear",
        titleKey: "gear",
        titleFallback: "Gear",
        icon: "🧥",
        description: "config.db.gear.description",
      },
      {
        href: "/db/traits",
        type: "traits",
        titleKey: "traits",
        titleFallback: "Traits",
        icon: "🧵",
        description: "config.db.traits.description",
      },
      {
        href: "/db/potions",
        type: "potions",
        titleKey: "potions",
        titleFallback: "Potions",
        icon: "🧪",
        description: "config.db.potions.description",
      },
      {
        href: "/db/plants",
        type: "plants",
        titleKey: "plants",
        titleFallback: "Plants",
        icon: "🌱",
        description: "config.db.plants.description",
      },
      {
        href: "/db/ingredients",
        type: "ingredients",
        titleKey: "ingredients",
        titleFallback: "Ingredients",
        icon: "🍄",
        description: "config.db.ingredients.description",
      },
      {
        href: "/db/beasts",
        type: "beasts",
        titleKey: "beasts",
        titleFallback: "Beasts",
        icon: "🦄",
        description: "config.db.beasts.description",
      },
      {
        href: "/db/enemies",
        type: "enemies",
        titleKey: "enemies",
        titleFallback: "Enemies",
        icon: "🕷️",
        description: "config.db.enemies.description",
      },
      {
        href: "/db/dungeons",
        type: "dungeons",
        titleKey: "dungeons",
        titleFallback: "Dungeons",
        icon: "🏰",
        description: "config.db.dungeons.description",
      },
      {
        href: "/db/quests",
        type: "quests",
        titleKey: "quests",
        titleFallback: "Quests",
        icon: "📜",
        description: "config.db.quests.description",
      },
      {
        href: "/db/challenges",
        type: "challenges",
        titleKey: "challenges",
        titleFallback: "Challenges",
        icon: "🏆",
        description: "config.db.challenges.description",
      },
      {
        href: "/db/field_guide",
        type: "field_guide",
        titleKey: "field_guide",
        titleFallback: "Revelio Pages",
        icon: "📖",
        description: "config.db.field_guide.description",
      },
      {
        href: "/db/conjurations",
        type: "conjurations",
        titleKey: "conjurations",
        titleFallback: "Conjurations",
        icon: "🪑",
        description: "config.db.conjurations.description",
      },
      {
        href: "/db/brooms",
        type: "brooms",
        titleKey: "brooms",
        titleFallback: "Brooms",
        icon: "🧹",
        description: "config.db.brooms.description",
      },
      {
        href: "/db/wand_handles",
        type: "wand_handles",
        titleKey: "wand_handles",
        titleFallback: "Wand Handles",
        icon: "✨",
        description: "config.db.wand_handles.description",
      },
      {
        href: "/db/merlin_trials",
        type: "merlin_trials",
        titleKey: "merlin_trials",
        titleFallback: "Merlin Trials",
        icon: "🗿",
        description: "config.db.merlin_trials.description",
      },
      {
        href: "/db/demiguise_statues",
        type: "demiguise_statues",
        titleKey: "demiguise_statues",
        titleFallback: "Demiguise Statues",
        icon: "🌙",
        description: "config.db.demiguise_statues.description",
      },
      {
        href: "/db/astronomy_tables",
        type: "astronomy_tables",
        titleKey: "astronomy_tables",
        titleFallback: "Astronomy Tables",
        icon: "🔭",
        description: "config.db.astronomy_tables.description",
      },
      {
        href: "/db/ancient_magic_hotspots",
        type: "ancient_magic_hotspots",
        titleKey: "ancient_magic_hotspots",
        titleFallback: "Ancient Magic Hotspots",
        icon: "💫",
        description: "config.db.ancient_magic_hotspots.description",
      },
      {
        href: "/db/treasure_vaults",
        type: "treasure_vaults",
        titleKey: "treasure_vaults",
        titleFallback: "Treasure Vaults",
        icon: "💰",
        description: "config.db.treasure_vaults.description",
      },
      {
        href: "/db/balloon_challenges",
        type: "balloon_challenges",
        titleKey: "balloon_challenges",
        titleFallback: "Balloon Sets",
        icon: "🎈",
        description: "config.db.balloon_challenges.description",
      },
      {
        href: "/db/landing_platforms",
        type: "landing_platforms",
        titleKey: "landing_platforms",
        titleFallback: "Landing Platforms",
        icon: "🛬",
        description: "config.db.landing_platforms.description",
      },
    ],
  },
};
