import { resolveAppConfig, DATA_FORGE_CDN_URL } from "@repo/lib";

// Inlined per-map preview URLs. The first one keeps the ?v=2 cache buster.
const preview = (mapId: string, version?: string) => {
  const url = `${DATA_FORGE_CDN_URL}/infinity-nikki/map-tiles/${mapId}/preview.webp`;
  return version ? `${url}?v=${version}` : url;
};

export const infinityNikki = resolveAppConfig({
  name: "infinity-nikki",
  // = the dicts data-forge emits (dicts/<locale>.json + dicts/db/<locale>.json).
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "id",
    "it",
    "ja",
    "ko",
    "pt",
    "th",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "Miraland Map",
      description: "config.internalLinks.maps-Miraland.description",
      href: "/maps/Miraland",
      iconName: "Map",
      bgImage: preview("1", "2"),
      linkText: "config.internalLinks.maps-Miraland.linkText",
    },
    {
      title: "Wanxiang Realm Map",
      description: "config.internalLinks.maps-Wanxiang%20Realm.description",
      href: "/maps/Wanxiang%20Realm",
      iconName: "Map",
      bgImage: preview("4020034"),
      linkText: "config.internalLinks.maps-Wanxiang%20Realm.linkText",
    },
    {
      title: "Danqing Island Map",
      description: "config.internalLinks.maps-Danqing%20Island.description",
      href: "/maps/Danqing%20Island",
      iconName: "Map",
      bgImage: preview("10000010"),
      linkText: "config.internalLinks.maps-Danqing%20Island.linkText",
    },
    {
      title: "Danqing Realm Map",
      description: "config.internalLinks.maps-Danqing%20Realm.description",
      href: "/maps/Danqing%20Realm",
      iconName: "Map",
      bgImage: preview("10000027"),
      linkText: "config.internalLinks.maps-Danqing%20Realm.linkText",
    },
    {
      title: "Firework Isles Map",
      description: "config.internalLinks.maps-Firework%20Isles.description",
      href: "/maps/Firework%20Isles",
      iconName: "Map",
      bgImage: preview("10000001"),
      linkText: "config.internalLinks.maps-Firework%20Isles.linkText",
    },
    {
      title: "Serenity Island Map",
      description: "config.internalLinks.maps-Serenity%20Island.description",
      href: "/maps/Serenity%20Island",
      iconName: "Map",
      bgImage: preview("10000002"),
      linkText: "config.internalLinks.maps-Serenity%20Island.linkText",
    },
    {
      title: "Sea of Stars Map",
      description: "config.internalLinks.maps-Sea%20of%20Stars.description",
      href: "/maps/Sea%20of%20Stars",
      iconName: "Map",
      bgImage: preview("14000000"),
      linkText: "config.internalLinks.maps-Sea%20of%20Stars.linkText",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
    {
      href: "/activities-tracker",
      title: "activities.navTitle",
      description: "activities.navDescription",
      linkText: "activities.navLinkText",
      iconName: "Activity",
    },
  ],
  externalLinks: [],
  keywords: [
    "Whimstar & Whim Balloon spots",
    "Dew of Inspiration & Dew of Firework routes",
    "Wanxiang Bell & Whim Lantern locations",
    "Outfit & clothing database",
  ],
  db: {
    // Collection checklists (/checklist, /checklist/<section>).
    checklists: [
      { section: "outfit-sets" },
      { section: "clothing" },
      { section: "momo-wardrobe" },
    ],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/outfit-sets",
        type: "outfit-sets",
        titleKey: "config.db.outfit-sets.title",
        titleFallback: "Outfits",
        icon: "👗",
        description: "config.db.outfit-sets.description",
      },
      {
        href: "/db/clothing",
        type: "clothing",
        titleKey: "config.db.clothing.title",
        titleFallback: "Clothing",
        icon: "👚",
        description: "config.db.clothing.description",
      },
      {
        href: "/db/accessories",
        type: "accessories",
        titleKey: "config.db.accessories.title",
        titleFallback: "Accessories",
        icon: "💍",
        description: "config.db.accessories.description",
      },
      {
        href: "/db/makeup",
        type: "makeup",
        titleKey: "config.db.makeup.title",
        titleFallback: "Makeup",
        icon: "💄",
        description: "config.db.makeup.description",
      },
      {
        href: "/db/abilities",
        type: "abilities",
        titleKey: "config.db.abilities.title",
        titleFallback: "Abilities",
        icon: "✨",
        description: "config.db.abilities.description",
      },
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "config.db.inventory.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/shops",
        type: "shops",
        titleKey: "config.db.shops.title",
        titleFallback: "Shops",
        icon: "🛍️",
        description: "config.db.shops.description",
      },
      {
        href: "/db/eureka",
        type: "eureka",
        titleKey: "config.db.eureka.title",
        titleFallback: "Eureka",
        icon: "🌟",
        description: "config.db.eureka.description",
      },
      {
        href: "/db/momo-wardrobe",
        type: "momo-wardrobe",
        titleKey: "config.db.momo-wardrobe.title",
        titleFallback: "Momo's Wardrobe",
        icon: "🐱",
        description: "config.db.momo-wardrobe.description",
      },
      {
        href: "/db/labels",
        type: "labels",
        titleKey: "config.db.labels.title",
        titleFallback: "Labels",
        icon: "🏷️",
        description: "config.db.labels.description",
      },
    ],
    typeLabels: {
      "outfit-sets": "config.db.typeLabels.outfit-sets",
      clothing: "config.db.typeLabels.clothing",
      accessories: "config.db.typeLabels.accessories",
      makeup: "config.db.typeLabels.makeup",
      abilities: "config.db.typeLabels.abilities",
      inventory: "config.db.typeLabels.inventory",
      eureka: "config.db.typeLabels.eureka",
      "momo-wardrobe": "config.db.typeLabels.momo-wardrobe",
      shops: "config.db.typeLabels.shops",
      labels: "config.db.typeLabels.labels",
    },
  },
});
