import { resolveAppConfig } from "@repo/lib";

export const minecraftDungeons2 = resolveAppConfig({
  name: "minecraft-dungeons-2",
  // Locales the game ships (Localization/All/<culture>) that the THGL UI also supports.
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "it",
    "ja",
    "ko",
    "pl",
    "pt-BR",
    "ru",
    "tr",
    "uk",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  withoutLiveMode: true,
  internalLinks: [
    {
      title: "Weapons & Armor",
      description:
        "Every melee weapon, ranged weapon and armor piece in Minecraft Dungeons II — with combo damage, gear effects, unique versions and where each one drops.",
      href: "/db/melee_weapons",
      iconName: "Axe",
      linkText: "Browse Weapons",
    },
    {
      title: "Enchantments",
      description:
        "All enchantments, gear effects and soul enchantments, with what they do and which status effects they apply.",
      href: "/db/enchantments",
      iconName: "Sparkles",
      linkText: "Browse Enchantments",
    },
    {
      title: "Mobs",
      description:
        "The bestiary: hostile mobs, soul-corrupted variants, bosses and creatures — with health, speed and the areas they spawn in.",
      href: "/db/mobs",
      iconName: "Bug",
      linkText: "Browse Mobs",
    },
    {
      title: "Quests",
      description:
        "Core and side quests with objectives, rewards, prerequisites and quest-giver locations.",
      href: "/db/quest_log",
      iconName: "ScrollText",
      linkText: "Browse Quests",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Minecart Stations",
    "Dungeons",
    "Rifts",
    "Chests",
    "Soul Storms",
    "Merchants",
  ],
  topFilters: [
    "minecart_station",
    "dungeon",
    "rift",
    "fancy_chest",
    "talisman_chest",
  ],
  db: {
    heroSubtitle: "Game Database",
    searchPlaceholder: "Search weapons, armor, mobs…",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/melee_weapons",
        type: "melee_weapons",
        titleFallback: "Melee Weapons",
        icon: "⚔️",
        description:
          "Swords, axes, hammers, daggers and their unique versions.",
      },
      {
        href: "/db/ranged_weapons",
        type: "ranged_weapons",
        titleFallback: "Ranged Weapons",
        icon: "🏹",
        description: "Bows and crossbows.",
      },
      {
        href: "/db/armor",
        type: "armor",
        titleFallback: "Armor",
        icon: "🛡️",
        description:
          "Helmets, chestplates, leggings and boots, grouped into sets.",
      },
      {
        href: "/db/gear_artifacts",
        type: "gear_artifacts",
        titleFallback: "Artifacts",
        icon: "🔮",
        description: "Artifacts with cooldowns and soul costs.",
      },
      {
        href: "/db/talismans",
        type: "talismans",
        titleFallback: "Talismans",
        icon: "📿",
        description: "Talismans, their levels and the quests that reward them.",
      },
      {
        href: "/db/enchantments",
        type: "enchantments",
        titleFallback: "Enchantments",
        icon: "✨",
        description: "Enchantments and the gear slots they apply to.",
      },
      {
        href: "/db/gear_effects",
        type: "gear_effects",
        titleFallback: "Gear Effects",
        icon: "💠",
        description: "The effects that roll on gear.",
      },
      {
        href: "/db/soul_enchantments",
        type: "soul_enchantments",
        titleFallback: "Soul Enchantments",
        icon: "👻",
        description: "Powers of soul-corrupted mobs.",
      },
      {
        href: "/db/status_effects",
        type: "status_effects",
        titleFallback: "Status Effects",
        icon: "🔥",
        description: "Burning, poison, freezing and every other status.",
      },
      {
        href: "/db/mobs",
        type: "mobs",
        titleFallback: "Mobs",
        icon: "💀",
        description: "Hostile mobs, bosses, companions and creatures.",
      },
      {
        href: "/db/quest_log",
        type: "quest_log",
        titleFallback: "Quests",
        icon: "📜",
        description: "Core and side quests with objectives and rewards.",
      },
      {
        href: "/db/consumables",
        type: "consumables",
        titleFallback: "Consumables",
        icon: "🍎",
        description: "Food and throwables.",
      },
      {
        href: "/db/cosmetics",
        type: "cosmetics",
        titleFallback: "Capes & Pets",
        icon: "🧣",
        description: "Capes and pets.",
      },
    ],
    typeLabels: {
      melee_weapons: "Melee Weapons",
      ranged_weapons: "Ranged Weapons",
      armor: "Armor",
      gear_artifacts: "Artifacts",
      talismans: "Talismans",
      enchantments: "Enchantments",
      gear_effects: "Gear Effects",
      soul_enchantments: "Soul Enchantments",
      status_effects: "Status Effects",
      mobs: "Mobs",
      quest_log: "Quests",
      consumables: "Consumables",
      cosmetics: "Capes & Pets",
    },
  },
});
