import { resolveAppConfig } from "@repo/lib";

export const minecraftDungeons2 = resolveAppConfig({
  name: "minecraft-dungeons-2",
  // Locales the game ships (Localization/All/<culture>) that the THGL UI also supports.
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "it",
    "ja",
    "ko",
    "pl",
    "pt-BR",
    "ru",
    "tr",
    "uk",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  withoutLiveMode: true,
  internalLinks: [
    {
      title: "config.internalLinks.melee_weapons.title",
      description: "config.internalLinks.melee_weapons.description",
      href: "/db/melee_weapons",
      iconName: "Axe",
      linkText: "config.internalLinks.melee_weapons.linkText",
    },
    {
      title: "config.internalLinks.enchantments.title",
      description: "config.internalLinks.enchantments.description",
      href: "/db/enchantments",
      iconName: "Sparkles",
      linkText: "config.internalLinks.enchantments.linkText",
    },
    {
      title: "config.internalLinks.mobs.title",
      description: "config.internalLinks.mobs.description",
      href: "/db/mobs",
      iconName: "Bug",
      linkText: "config.internalLinks.mobs.linkText",
    },
    {
      title: "config.internalLinks.quest_log.title",
      description: "config.internalLinks.quest_log.description",
      href: "/db/quest_log",
      iconName: "ScrollText",
      linkText: "config.internalLinks.quest_log.linkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Minecart Stations",
    "Dungeons",
    "Rifts",
    "Chests",
    "Soul Storms",
    "Merchants",
  ],
  topFilters: [
    "minecart_station",
    "dungeon",
    "rift",
    "fancy_chest",
    "talisman_chest",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/melee_weapons",
        type: "melee_weapons",
        titleKey: "config.db.melee_weapons.title",
        titleFallback: "Melee Weapons",
        icon: "⚔️",
        description: "config.db.melee_weapons.description",
      },
      {
        href: "/db/ranged_weapons",
        type: "ranged_weapons",
        titleKey: "config.db.ranged_weapons.title",
        titleFallback: "Ranged Weapons",
        icon: "🏹",
        description: "config.db.ranged_weapons.description",
      },
      {
        href: "/db/armor",
        type: "armor",
        titleKey: "config.db.armor.title",
        titleFallback: "Armor",
        icon: "🛡️",
        description: "config.db.armor.description",
      },
      {
        href: "/db/gear_artifacts",
        type: "gear_artifacts",
        titleKey: "config.db.gear_artifacts.title",
        titleFallback: "Artifacts",
        icon: "🔮",
        description: "config.db.gear_artifacts.description",
      },
      {
        href: "/db/talismans",
        type: "talismans",
        titleKey: "config.db.talismans.title",
        titleFallback: "Talismans",
        icon: "📿",
        description: "config.db.talismans.description",
      },
      {
        href: "/db/enchantments",
        type: "enchantments",
        titleKey: "config.internalLinks.enchantments.title",
        titleFallback: "Enchantments",
        icon: "✨",
        description: "config.db.enchantments.description",
      },
      {
        href: "/db/gear_effects",
        type: "gear_effects",
        titleKey: "config.db.gear_effects.title",
        titleFallback: "Gear Effects",
        icon: "💠",
        description: "config.db.gear_effects.description",
      },
      {
        href: "/db/soul_enchantments",
        type: "soul_enchantments",
        titleKey: "config.db.soul_enchantments.title",
        titleFallback: "Soul Enchantments",
        icon: "👻",
        description: "config.db.soul_enchantments.description",
      },
      {
        href: "/db/status_effects",
        type: "status_effects",
        titleKey: "config.db.status_effects.title",
        titleFallback: "Status Effects",
        icon: "🔥",
        description: "config.db.status_effects.description",
      },
      {
        href: "/db/mobs",
        type: "mobs",
        titleKey: "config.internalLinks.mobs.title",
        titleFallback: "Mobs",
        icon: "💀",
        description: "config.db.mobs.description",
      },
      {
        href: "/db/quest_log",
        type: "quest_log",
        titleKey: "config.internalLinks.quest_log.title",
        titleFallback: "Quests",
        icon: "📜",
        description: "config.db.quest_log.description",
      },
      {
        href: "/db/consumables",
        type: "consumables",
        titleKey: "config.db.consumables.title",
        titleFallback: "Consumables",
        icon: "🍎",
        description: "config.db.consumables.description",
      },
      {
        href: "/db/cosmetics",
        type: "cosmetics",
        titleKey: "config.db.cosmetics.title",
        titleFallback: "Capes & Pets",
        icon: "🧣",
        description: "config.db.cosmetics.description",
      },
    ],
    typeLabels: {
      melee_weapons: "config.db.typeLabels.melee_weapons",
      ranged_weapons: "config.db.typeLabels.ranged_weapons",
      armor: "config.db.typeLabels.armor",
      gear_artifacts: "config.db.typeLabels.gear_artifacts",
      talismans: "config.db.typeLabels.talismans",
      enchantments: "config.db.typeLabels.enchantments",
      gear_effects: "config.db.typeLabels.gear_effects",
      soul_enchantments: "config.db.typeLabels.soul_enchantments",
      status_effects: "config.db.typeLabels.status_effects",
      mobs: "config.db.typeLabels.mobs",
      quest_log: "config.db.typeLabels.quest_log",
      consumables: "config.db.typeLabels.consumables",
      cosmetics: "config.db.typeLabels.cosmetics",
    },
  },
});
