import { resolveAppConfig } from "@repo/lib";

export const nevernessToEverness = resolveAppConfig({
  name: "neverness-to-everness",
  // Map markers use English category labels; the database/codex below is localized
  // across all 8 locales the game ships (dicts/*.json).
  supportedLocales: ["en", "de", "es", "fr", "ja", "ko", "ru", "zh-CN"],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "config.internalLinks.characters.title",
      description: "config.internalLinks.characters.description",
      href: "/db/characters",
      iconName: "Heart",
      linkText: "config.internalLinks.characters.linkText",
    },
    {
      title: "config.internalLinks.arcs.title",
      description: "config.internalLinks.arcs.description",
      href: "/db/arcs",
      iconName: "Axe",
      linkText: "config.internalLinks.arcs.linkText",
    },
    {
      title: "config.internalLinks.cartridges.title",
      description: "config.internalLinks.cartridges.description",
      href: "/db/cartridges",
      iconName: "Grid",
      linkText: "config.internalLinks.cartridges.linkText",
    },
    {
      title: "config.internalLinks.vehicles.title",
      description: "config.internalLinks.vehicles.description",
      href: "/db/vehicles",
      iconName: "Server",
      linkText: "config.internalLinks.vehicles.linkText",
    },
    {
      title: "config.internalLinks.visions.title",
      description: "config.internalLinks.visions.description",
      href: "/db/visions",
      iconName: "BookOpen",
      linkText: "config.internalLinks.visions.linkText",
    },
    {
      title: "config.internalLinks.bestiary.title",
      description: "config.internalLinks.bestiary.description",
      href: "/db/bestiary",
      iconName: "Bug",
      linkText: "config.internalLinks.bestiary.linkText",
    },
    {
      title: "config.internalLinks.items.title",
      description: "config.internalLinks.items.description",
      href: "/db/items",
      iconName: "Hammer",
      linkText: "config.internalLinks.items.linkText",
    },
    {
      title: "config.internalLinks.properties.title",
      description: "config.internalLinks.properties.description",
      href: "/db/properties",
      iconName: "House",
      linkText: "config.internalLinks.properties.linkText",
    },
    {
      title: "config.internalLinks.achievements.title",
      description: "config.internalLinks.achievements.description",
      href: "/db/achievements",
      iconName: "Trophy",
      linkText: "config.internalLinks.achievements.linkText",
    },
    {
      title: "config.internalLinks.quests.title",
      description: "config.internalLinks.quests.description",
      href: "/db/quests",
      iconName: "ScrollText",
      linkText: "config.internalLinks.quests.linkText",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Characters",
    "Arcs",
    "Cartridges",
    "Anomaly Archive",
    "Bestiary",
    "Items",
    "Properties",
    "Achievements",
    "Quests",
  ],
  topFilters: [
    "treasure_box",
    "treasure_gift21",
    "oracle_stone",
    "vision_soul",
  ],
  db: {
    // Achievement tracker: every achievement with its in-game tab, the
    // condition text and the Annulith it pays out (earned / all).
    checklists: [
      {
        section: "achievements",
        descriptions: true,
        rewardTotals: ["item_Annulith"],
      },
    ],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/characters",
        type: "characters",
        titleKey: "config.internalLinks.characters.title",
        titleFallback: "Characters",
        icon: "🧑",
        description: "config.db.characters.description",
      },
      {
        href: "/db/arcs",
        type: "arcs",
        titleKey: "config.internalLinks.arcs.title",
        titleFallback: "Arcs (Weapons)",
        icon: "⚔️",
        description: "config.db.arcs.description",
      },
      {
        href: "/db/cartridges",
        type: "cartridges",
        titleKey: "config.internalLinks.cartridges.title",
        titleFallback: "Cartridges",
        icon: "🔲",
        description: "config.internalLinks.cartridges.description",
      },
      {
        href: "/db/vehicles",
        type: "vehicles",
        titleKey: "config.internalLinks.vehicles.title",
        titleFallback: "Vehicles",
        icon: "🚗",
        description: "config.internalLinks.vehicles.description",
      },
      {
        href: "/db/visions",
        type: "visions",
        titleKey: "config.internalLinks.visions.title",
        titleFallback: "Anomaly Archive",
        icon: "📖",
        description: "config.db.visions.description",
      },
      {
        href: "/db/bestiary",
        type: "bestiary",
        titleKey: "config.internalLinks.bestiary.title",
        titleFallback: "Bestiary",
        icon: "👹",
        description: "config.db.bestiary.description",
      },
      {
        href: "/db/items",
        type: "items",
        titleKey: "config.internalLinks.items.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.items.description",
      },
      {
        href: "/db/properties",
        type: "properties",
        titleKey: "config.internalLinks.properties.title",
        titleFallback: "Properties",
        icon: "🏠",
        description: "config.db.properties.description",
      },
      {
        href: "/db/achievements",
        type: "achievements",
        titleKey: "config.internalLinks.achievements.title",
        titleFallback: "Achievements",
        icon: "🏆",
        description: "config.db.achievements.description",
      },
      {
        href: "/db/quests",
        type: "quests",
        titleKey: "config.internalLinks.quests.title",
        titleFallback: "Quests",
        icon: "📜",
        description: "config.db.quests.description",
      },
    ],
    typeLabels: {
      characters: "config.db.typeLabels.characters",
      arcs: "config.db.typeLabels.arcs",
      cartridges: "config.db.typeLabels.cartridges",
      vehicles: "config.db.typeLabels.vehicles",
      visions: "config.db.typeLabels.visions",
      bestiary: "config.db.typeLabels.bestiary",
      items: "config.db.typeLabels.items",
      properties: "config.db.typeLabels.properties",
      achievements: "config.db.typeLabels.achievements",
      quests: "config.db.typeLabels.quests",
    },
  },
});
