import { resolveAppConfig } from "@repo/lib";

// Maps are NOT listed here: the home page auto-generates a card per map in
// version.data.tiles (localized names). Link texts are once-human UI dict keys.
export const onceHuman = resolveAppConfig({
  name: "once-human",
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "ja",
    "ko",
    "pt",
    "ru",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
    {
      title: "blueprints.navTitle",
      description: "blueprints.navDescription",
      href: "/blueprints",
      bgImage: "/games/thgl-web/tools/blueprints.webp",
      iconName: "Sparkles",
      linkText: "blueprints.navLinkText",
    },
    {
      href: "/db/blueprints",
      title: "oh.link.blueprints_db.title",
      description: "oh.link.blueprints_db.description",
      iconName: "FileText",
      linkText: "oh.link.blueprints_db.linkText",
    },
    {
      href: "/db/materials",
      title: "oh.link.materials.title",
      description: "oh.link.materials.description",
      iconName: "Gift",
      linkText: "oh.link.materials.linkText",
    },
    {
      href: "/db/consumables",
      title: "oh.link.consumables.title",
      description: "oh.link.consumables.description",
      iconName: "ChefHat",
      linkText: "oh.link.consumables.linkText",
    },
    {
      href: "/db/gear",
      title: "oh.link.gear.title",
      description: "oh.link.gear.description",
      iconName: "Shield",
      linkText: "oh.link.gear.linkText",
    },
    {
      href: "/db/facilities",
      title: "oh.link.facilities.title",
      description: "oh.link.facilities.description",
      iconName: "House",
      linkText: "oh.link.facilities.linkText",
    },
    {
      href: "/db/vehicles",
      title: "oh.link.vehicles.title",
      description: "oh.link.vehicles.description",
      iconName: "Grid",
      linkText: "oh.link.vehicles.linkText",
    },
    {
      href: "/db/alternate-recipes",
      title: "oh.link.alternate_recipes.title",
      description: "oh.link.alternate_recipes.description",
      iconName: "ScrollText",
      linkText: "oh.link.alternate_recipes.linkText",
    },
    {
      href: "/db/mod-locations",
      title: "oh.link.mod_locations.title",
      iconName: "ArrowUp",
      linkText: "oh.link.mod_locations.linkText",
    },
    {
      href: "/db/deviant-locations",
      title: "oh.link.deviant_locations.title",
      iconName: "Bug",
      linkText: "oh.link.deviant_locations.linkText",
    },
    {
      href: "/db/remnants",
      title: "oh.link.remnants.title",
      iconName: "NotepadText",
      linkText: "oh.link.remnants.linkText",
    },
    {
      href: "/db/regional-records",
      title: "oh.link.regional_records.title",
      iconName: "NotepadText",
      linkText: "oh.link.regional_records.linkText",
    },
    {
      href: "/db/echoes-of-stardust",
      title: "oh.link.echoes.title",
      iconName: "NotepadText",
      linkText: "oh.link.echoes.linkText",
    },
    {
      href: "/db/weapons",
      title: "oh.link.weapons.title",
      iconName: "Axe",
      linkText: "oh.link.weapons.linkText",
    },
  ],
  keywords: ["Ores", "Resources", "Riddles", "Deviants"],
  topFilters: [
    "mystical_crate",
    "landscape_viewpoint_camera",
    "hoard_loot_crate",
  ],
  db: {
    // One indexable /blueprints/<id> page per blueprint (sitemap + codex link).
    entryPages: [
      {
        type: "blueprints",
        path: "/blueprints",
        labelKey: "blueprints.dbLink",
      },
    ],
    heroSubtitle: "oh.db.heroSubtitle",
    searchPlaceholder: "oh.db.searchPlaceholder",
    homeSections: [
      {
        href: "/db/materials",
        type: "materials",
        icon: "⛏",
        titleFallback: "Materials",
        description: "oh.section.materials.description",
      },
      {
        href: "/db/consumables",
        type: "consumables",
        icon: "🍲",
        titleFallback: "Consumables",
        description: "oh.section.consumables.description",
      },
      {
        href: "/db/gear",
        type: "gear",
        icon: "🛡",
        titleFallback: "Gear",
        description: "oh.section.gear.description",
      },
      {
        href: "/db/facilities",
        type: "facilities",
        icon: "🏗",
        titleFallback: "Facilities",
        description: "oh.section.facilities.description",
      },
      {
        href: "/db/vehicles",
        type: "vehicles",
        icon: "🚙",
        titleFallback: "Vehicles",
        description: "oh.section.vehicles.description",
      },
      {
        href: "/db/blueprints",
        type: "blueprints",
        icon: "★",
        titleFallback: "Blueprints",
        description: "oh.section.blueprints_db.description",
      },
      {
        href: "/db/alternate-recipes",
        type: "alternate-recipes",
        icon: "📜",
        titleFallback: "Alternate Recipes",
        description: "oh.section.alternate_recipes.description",
      },
      {
        href: "/db/weapons",
        type: "weapon",
        icon: "⚔",
        titleFallback: "Weapons",
      },
      {
        href: "/db/remnants",
        type: "remnants",
        typePrefix: "remnants_",
        icon: "📓",
        titleFallback: "Remnants",
      },
      {
        href: "/db/regional-records",
        type: "regional_records",
        typePrefix: "regional_records_",
        icon: "🗺",
        titleFallback: "Regional Records",
      },
      {
        href: "/db/echoes-of-stardust",
        type: "echoes_of_stardust",
        typePrefix: "echoes_of_stardust_",
        icon: "✦",
        titleFallback: "Echoes of Stardust",
      },
    ],
    homeExtraLinks: [
      {
        href: "/db/mod-locations",
        title: "oh.extra.mod_locations.title",
        description: "oh.extra.mod_locations.description",
        icon: "⬆",
      },
      {
        href: "/db/deviant-locations",
        title: "oh.extra.deviant_locations.title",
        description: "oh.extra.deviant_locations.description",
        icon: "🐛",
      },
    ],
    typeLabels: {
      materials: "oh.type.materials",
      consumables: "oh.type.consumables",
      gear: "oh.type.gear",
      facilities: "oh.type.facilities",
      vehicles: "oh.type.vehicles",
      "alternate-recipes": "oh.type.alternate_recipes",
      blueprints: "oh.type.blueprints",
      weapon: "oh.type.weapon",
      remnants: "oh.type.remnants",
      regional_records: "oh.type.regional_records",
      echoes_of_stardust: "oh.type.echoes_of_stardust",
    },
    typeColors: {
      materials: "bg-stone-800/60 text-stone-300",
      consumables: "bg-lime-900/40 text-lime-400",
      gear: "bg-sky-900/40 text-sky-400",
      facilities: "bg-amber-900/40 text-amber-400",
      vehicles: "bg-teal-900/40 text-teal-400",
      "alternate-recipes": "bg-violet-900/40 text-violet-400",
      blueprints: "bg-yellow-900/40 text-yellow-400",
      weapon: "bg-orange-900/40 text-orange-400",
      remnants: "bg-emerald-900/40 text-emerald-400",
      regional_records: "bg-cyan-900/40 text-cyan-400",
      echoes_of_stardust: "bg-indigo-900/40 text-indigo-400",
    },
  },
});
