import { resolveAppConfig, DATA_FORGE_CDN_URL } from "@repo/lib";

const preview = (mapId: string) =>
  `${DATA_FORGE_CDN_URL}/palia/map-tiles/${mapId}/preview.webp`;

export const palia = resolveAppConfig({
  name: "palia",
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "it",
    "ja",
    "ko",
    "pt-BR",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  internalLinks: [
    {
      href: "/maps/Royal%20Highlands",
      title: "config.internalLinks.royalHighlands.title",
      description: "config.internalLinks.royalHighlands.description",
      linkText: "config.internalLinks.royalHighlands.linkText",
      iconName: "Map",
      bgImage: preview("AZ3_Root"),
    },
    {
      href: "/maps/Elderwood",
      title: "config.internalLinks.elderwood.title",
      description: "config.internalLinks.elderwood.description",
      linkText: "config.internalLinks.elderwood.linkText",
      iconName: "Map",
      bgImage: preview("AZ2_Root"),
    },
    {
      href: "/maps/Kilima%20Village",
      title: "config.internalLinks.kilima.title",
      description: "config.internalLinks.kilima.description",
      linkText: "config.internalLinks.kilima.linkText",
      iconName: "Map",
      bgImage: preview("VillageWorld"),
    },
    {
      href: "/maps/Bahari%20Bay",
      title: "config.internalLinks.bahari.title",
      description: "config.internalLinks.bahari.description",
      linkText: "config.internalLinks.bahari.linkText",
      iconName: "Map",
      bgImage: preview("AdventureZoneWorld"),
    },
    {
      href: "/maps/Fairgrounds",
      title: "config.internalLinks.fairgrounds.title",
      description: "config.internalLinks.fairgrounds.description",
      linkText: "config.internalLinks.fairgrounds.linkText",
      iconName: "Map",
      bgImage: preview("MajiMarket"),
    },
    {
      href: "/rummage-pile",
      title: "config.internalLinks.rummagePile.title",
      description: "config.internalLinks.rummagePile.description",
      linkText: "config.internalLinks.rummagePile.linkText",
      iconName: "MapPin",
      bgImage: "/games/thgl-web/tools/rummage-pile.webp",
    },
    {
      href: "/worlds",
      title: "config.internalLinks.activeWorlds.title",
      description: "config.internalLinks.activeWorlds.description",
      linkText: "config.internalLinks.activeWorlds.linkText",
      iconName: "Server",
      bgImage: "/games/thgl-web/tools/worlds.webp",
    },
    {
      href: "/leaderboard",
      title: "config.internalLinks.leaderboard.title",
      description: "config.internalLinks.leaderboard.description",
      linkText: "config.internalLinks.leaderboard.linkText",
      iconName: "Trophy",
      bgImage: "/games/thgl-web/tools/leaderboard.webp",
    },
    {
      href: "/weekly-wants",
      title: "config.internalLinks.weeklyWants.title",
      description: "config.internalLinks.weeklyWants.description",
      linkText: "config.internalLinks.weeklyWants.linkText",
      iconName: "Gift",
      bgImage: "/games/thgl-web/tools/weekly-wants.webp",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  keywords: ["Rummage Pile", "Plushies", "Elderwood"],
  // Fish and bug markers are where players caught or saw one, not fixed spawns.
  sightingFilters: ["cat_fishing", "cat_bugs"],
  // Only one-time spots get a progress tracker: everything else respawns.
  trackerFilters: [
    "treasures",
    "cat_decor",
    "discovery_quests",
    "bp_questitem_calerilvl3book",
    "bp_questitem_cookbook_1",
    "bp_questitem_cookbook_2",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "config.db.inventory.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/furniture",
        type: "furniture",
        titleKey: "config.db.furniture.title",
        titleFallback: "Furniture & Decor",
        icon: "🪑",
        description: "config.db.furniture.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.db.recipes.title",
        titleFallback: "Recipes",
        icon: "📜",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/fish",
        type: "fish",
        titleKey: "config.db.fish.title",
        titleFallback: "Fish",
        icon: "🐟",
        description: "config.db.fish.description",
      },
      {
        href: "/db/bugs",
        type: "bugs",
        titleKey: "config.db.bugs.title",
        titleFallback: "Bugs",
        icon: "🐞",
        description: "config.db.bugs.description",
      },
      {
        href: "/db/critters",
        type: "critters",
        titleKey: "config.db.critters.title",
        titleFallback: "Creatures",
        icon: "🏹",
        description: "config.db.critters.description",
      },
      {
        href: "/db/characters",
        type: "characters",
        titleKey: "weeklyWants.villagersAlt",
        titleFallback: "Villagers",
        icon: "🧑‍🌾",
        description: "config.db.characters.description",
      },
      {
        href: "/db/shops",
        type: "shops",
        titleKey: "config.db.shops.title",
        titleFallback: "Shops",
        icon: "🛒",
        description: "config.db.shops.description",
      },
    ],
    typeLabels: {
      inventory: "config.db.typeLabels.inventory",
      furniture: "config.db.typeLabels.furniture",
      recipes: "config.db.typeLabels.recipes",
      fish: "config.db.typeLabels.fish",
      bugs: "config.db.typeLabels.bugs",
      critters: "config.db.typeLabels.critters",
      characters: "config.db.typeLabels.characters",
      shops: "config.db.typeLabels.shops",
    },
  },
});
