import { resolveAppConfig } from "@repo/lib";

export const palworld = resolveAppConfig({
  name: "palworld",
  // Matches the locales the data-mining script emits (dicts/*.json) from the
  // extracted L10N cultures (extractor.jsonc → Pal/Content/L10N). Palworld ships
  // no Japanese.
  supportedLocales: [
    "en",
    "de",
    "es",
    "es-MX",
    "fr",
    "id",
    "it",
    "ko",
    "pl",
    "pt",
    "ru",
    "th",
    "tr",
    "vi",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  // No "/maps/..." internalLink: Palpagos Island and any future map auto-generate
  // from version.data.tiles (the auto-card is richer and is suppressed by a manual
  // same-target link). The links below point at the database (codex) sections.
  internalLinks: [
    {
      title: "breeding.title",
      description: "config.internalLinks.breeding.description",
      href: "/breeding",
      bgImage: "/games/thgl-web/tools/breeding.webp",
      iconName: "Heart",
      linkText: "config.internalLinks.breeding.linkText",
    },
    {
      title: "iv.navTitle",
      description: "iv.navDescription",
      href: "/iv-calculator",
      bgImage: "/games/thgl-web/tools/iv-calculator.webp",
      iconName: "ChartLine",
      linkText: "iv.navLinkText",
    },
    {
      title: "config.internalLinks.paldeck.title",
      description: "config.internalLinks.paldeck.description",
      href: "/db/paldeck",
      iconName: "Bug",
      linkText: "config.internalLinks.paldeck.linkText",
    },
    {
      title: "config.internalLinks.inventory.title",
      description: "config.internalLinks.inventory.description",
      href: "/db/inventory",
      iconName: "Gift",
      linkText: "config.internalLinks.inventory.linkText",
    },
    {
      title: "config.internalLinks.recipes.title",
      description: "config.internalLinks.recipes.description",
      href: "/db/recipes",
      iconName: "BookOpen",
      linkText: "config.internalLinks.recipes.linkText",
    },
    {
      title: "config.internalLinks.technology.title",
      description: "config.internalLinks.technology.description",
      href: "/db/technology",
      iconName: "Grid",
      linkText: "config.internalLinks.technology.linkText",
    },
    {
      title: "config.internalLinks.invaders.title",
      description: "config.internalLinks.invaders.description",
      href: "/db/invaders",
      iconName: "Axe",
      linkText: "config.internalLinks.invaders.linkText",
    },
    {
      title: "config.internalLinks.visitors.title",
      description: "config.internalLinks.visitors.description",
      href: "/db/visitors",
      iconName: "Users",
      linkText: "config.internalLinks.visitors.linkText",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  externalLinks: [],
  keywords: ["Tides of Terraria", "Feybreak", "Predator & Alpha Pals"],
  topFilters: [
    "lifmunk_effigy",
    "dungeon_random",
    "coal",
    "junk_yard",
    "boss_thunderbird",
    "predator_sifudog",
    "fasttravel",
    "skill_fruit",
  ],
  db: {
    // Collection checklists (/checklist, /checklist/<section>).
    checklists: [{ section: "paldeck" }],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    // One indexable /breeding/<palId> page per Paldeck entry (sitemap + codex link).
    entryPages: [
      { type: "paldeck", path: "/breeding", labelKey: "breeding.howToBreed" },
    ],
    homeSections: [
      {
        href: "/db/paldeck",
        type: "paldeck",
        titleKey: "config.internalLinks.paldeck.title",
        titleFallback: "Paldeck",
        icon: "🐾",
        description: "config.db.paldeck.description",
      },
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "config.internalLinks.inventory.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.internalLinks.recipes.title",
        titleFallback: "Recipes",
        icon: "📜",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/technology",
        type: "technology",
        titleKey: "config.internalLinks.technology.title",
        titleFallback: "Technology",
        icon: "🔧",
        description: "config.db.technology.description",
      },
      {
        href: "/db/invaders",
        type: "invaders",
        titleKey: "config.internalLinks.invaders.title",
        titleFallback: "Base Invaders",
        icon: "⚔️",
        description: "config.db.invaders.description",
      },
      {
        href: "/db/visitors",
        type: "visitors",
        titleKey: "config.internalLinks.visitors.title",
        titleFallback: "Base Visitors",
        icon: "🧳",
        description: "config.db.visitors.description",
      },
    ],
    typeLabels: {
      paldeck: "config.db.typeLabels.paldeck",
      inventory: "config.db.typeLabels.inventory",
      recipes: "config.db.typeLabels.recipes",
      technology: "config.db.typeLabels.technology",
      invaders: "config.db.typeLabels.invaders",
      visitors: "config.db.typeLabels.visitors",
    },
  },
});
