import { resolveAppConfig } from "@repo/lib";

export const planetCrafter = resolveAppConfig({
  name: "planet-crafter",
  supportedLocales: [
    "en",
    "fr",
    "es",
    "pt",
    "de",
    "zh-CN",
    "zh-TW",
    "ja",
    "ko",
    "pl",
    "ru",
    "tr",
    "it",
  ],
  appUrl: null,
  internalLinks: [
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Silicon",
    "Aluminum",
    "Ice",
    "Iridium",
    "Super Alloy",
    "Golden Crates",
    "Data Logs",
    "Resources",
  ],
  topFilters: ["Iridium", "Aluminium", "golden", "data_log", "fusion_reactor"],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "config.db.inventory.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/buildings",
        type: "buildings",
        titleKey: "config.db.buildings.title",
        titleFallback: "Buildings",
        icon: "🏭",
        description: "config.db.buildings.description",
      },
    ],
    typeLabels: {
      inventory: "config.db.typeLabels.inventory",
      buildings: "config.db.typeLabels.buildings",
    },
  },
});
