import { resolveAppConfig } from "@repo/lib";

export const satisfactory = resolveAppConfig({
  name: "satisfactory",
  supportedLocales: [
    "en",
    "cs",
    "de",
    "es",
    "es-MX",
    "fr",
    "hu",
    "id",
    "it",
    "ja",
    "ko",
    "pl",
    "pt",
    "ru",
    "th",
    "tr",
    "uk",
    "vi",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  keywords: ["Mercer Spheres", "Resource Nodes", "Power Slugs", "Hard Drives"],
  // List EVERY db section here (in homeSections order): the header renders
  // internalLinks before "All Guides" and appends any homeSections not linked
  // yet after it — a partial list splits the database links around "All Guides".
  internalLinks: [
    {
      title: "config.internalLinks.inventory.title",
      description: "config.internalLinks.inventory.description",
      href: "/db/inventory",
      iconName: "Gift",
      linkText: "config.internalLinks.inventory.linkText",
    },
    {
      title: "config.internalLinks.structures.title",
      description: "config.internalLinks.structures.description",
      href: "/db/structures",
      iconName: "House",
      linkText: "config.internalLinks.structures.linkText",
    },
    {
      title: "config.internalLinks.recipes.title",
      description: "config.internalLinks.recipes.description",
      href: "/db/recipes",
      iconName: "BookOpen",
      linkText: "config.internalLinks.recipes.linkText",
    },
    {
      title: "config.internalLinks.schematics.title",
      description: "config.internalLinks.schematics.description",
      href: "/db/schematics",
      iconName: "ScrollText",
      linkText: "config.internalLinks.schematics.linkText",
    },
    {
      title: "config.internalLinks.fauna.title",
      description: "config.internalLinks.fauna.description",
      href: "/db/fauna",
      iconName: "PawPrint",
      linkText: "config.internalLinks.fauna.linkText",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "config.internalLinks.inventory.title",
        titleFallback: "Items",
        icon: "📦",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/structures",
        type: "structures",
        titleKey: "config.internalLinks.structures.title",
        titleFallback: "Buildings",
        icon: "🏭",
        description: "config.db.structures.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.internalLinks.recipes.title",
        titleFallback: "Recipes",
        icon: "📜",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/schematics",
        type: "schematics",
        titleKey: "config.internalLinks.schematics.title",
        titleFallback: "Schematics",
        icon: "🔬",
        description: "config.db.schematics.description",
      },
      {
        href: "/db/fauna",
        type: "fauna",
        titleKey: "config.internalLinks.fauna.title",
        titleFallback: "Creatures",
        icon: "🐗",
        description: "config.db.fauna.description",
      },
    ],
    typeLabels: {
      inventory: "config.db.typeLabels.inventory",
      structures: "config.db.typeLabels.structures",
      recipes: "config.db.typeLabels.recipes",
      schematics: "config.db.typeLabels.schematics",
      fauna: "config.db.typeLabels.fauna",
    },
  },
});
