import { resolveAppConfig } from "@repo/lib";

/**
 * Songs of Conquest — database-only codex (migrated from the standalone
 * soc.th.gl site). Renders entirely through the generic `/db/[section]` +
 * `/db/[section]/[id]` routes and `GenericEntityView`; no per-game React code.
 *
 * Section slugs are intentionally singular (Gothic pattern) so they don't
 * collide with HoMM Olden Era's static `/db/units`, `/db/spells`, … route
 * folders (those `requireApp("homm-olden-era")` and 404 other tenants).
 */
export const songsOfConquest = resolveAppConfig({
  name: "songs-of-conquest",
  supportedLocales: [
    "en",
    "ru",
    "cs",
    "fr",
    "de",
    "it",
    "pl",
    "es",
    "zh-CN",
    "ja",
    "ko",
    "pt-BR",
    "uk",
  ],
  appUrl: null,
  internalLinks: [
    {
      href: "/db/unit",
      title: "config.internalLinks.unit.title",
      linkText: "config.internalLinks.unit.linkText",
      iconName: "Axe",
      description: "config.internalLinks.unit.description",
    },
    {
      href: "/db/wielder",
      title: "config.internalLinks.wielder.title",
      linkText: "config.internalLinks.wielder.linkText",
      iconName: "Trophy",
      description: "config.internalLinks.wielder.description",
    },
    {
      href: "/db/spell",
      title: "config.internalLinks.spell.title",
      linkText: "config.internalLinks.spell.linkText",
      iconName: "ScrollText",
      description: "config.internalLinks.spell.description",
    },
    {
      href: "/db/artifact",
      title: "config.internalLinks.artifact.title",
      linkText: "config.internalLinks.artifact.linkText",
      iconName: "Gift",
      description: "config.internalLinks.artifact.description",
    },
    {
      href: "/db/skill",
      title: "config.internalLinks.skill.title",
      linkText: "config.internalLinks.skill.linkText",
      iconName: "BookOpen",
      description: "config.internalLinks.skill.description",
    },
    {
      href: "/db/faction",
      title: "config.internalLinks.faction.title",
      linkText: "config.internalLinks.faction.linkText",
      iconName: "ShieldCheck",
      description: "config.internalLinks.faction.description",
    },
    {
      href: "/db/building",
      title: "config.internalLinks.building.title",
      linkText: "config.internalLinks.building.linkText",
      iconName: "House",
      description: "config.internalLinks.building.description",
    },
    {
      href: "/db/random-event",
      title: "config.internalLinks.random-event.title",
      linkText: "config.internalLinks.random-event.linkText",
      iconName: "FileText",
      description: "config.internalLinks.random-event.description",
    },
    {
      href: "/db/town",
      title: "config.internalLinks.town.title",
      linkText: "config.internalLinks.town.linkText",
      iconName: "House",
      description: "config.internalLinks.town.description",
    },
    {
      href: "/db/savegame",
      title: "config.internalLinks.savegame.title",
      linkText: "config.internalLinks.savegame.linkText",
      iconName: "NotepadText",
      description: "config.internalLinks.savegame.description",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Songs of Conquest",
    "SoC",
    "Database",
    "Codex",
    "Units",
    "Wielders",
    "Spells",
    "Artifacts",
    "Skills",
    "Factions",
    "Buildings",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    homeSections: [
      {
        href: "/db/unit",
        type: "units",
        titleKey: "config.internalLinks.unit.title",
        titleFallback: "Units",
        icon: "⚔",
      },
      {
        href: "/db/wielder",
        type: "wielders",
        titleKey: "config.internalLinks.wielder.title",
        titleFallback: "Wielders",
        icon: "👑",
      },
      {
        href: "/db/spell",
        type: "spells",
        titleKey: "config.internalLinks.spell.title",
        titleFallback: "Spells",
        icon: "✦",
      },
      {
        href: "/db/artifact",
        type: "artifacts",
        titleKey: "config.internalLinks.artifact.title",
        titleFallback: "Artifacts",
        icon: "◆",
      },
      {
        href: "/db/skill",
        type: "skills",
        titleKey: "config.internalLinks.skill.title",
        titleFallback: "Skills",
        icon: "◎",
      },
      {
        href: "/db/faction",
        type: "factions",
        titleKey: "config.internalLinks.faction.title",
        titleFallback: "Factions",
        icon: "⛊",
      },
      {
        href: "/db/building",
        type: "buildings",
        titleKey: "config.internalLinks.building.title",
        titleFallback: "Buildings",
        icon: "🏛",
      },
      {
        href: "/db/random-event",
        type: "random_events",
        titleKey: "config.internalLinks.random-event.title",
        titleFallback: "Random Events",
        icon: "🎲",
      },
      {
        href: "/db/town",
        type: "towns",
        titleKey: "config.internalLinks.town.title",
        titleFallback: "Town Builds",
        icon: "🏰",
      },
    ],
    typeLabels: {
      units: "config.db.typeLabels.units",
      wielders: "config.db.typeLabels.wielders",
      spells: "config.db.typeLabels.spells",
      artifacts: "config.db.typeLabels.artifacts",
      skills: "config.db.typeLabels.skills",
      factions: "config.db.typeLabels.factions",
      buildings: "config.db.typeLabels.buildings",
      random_events: "config.db.typeLabels.random_events",
      towns: "config.db.typeLabels.towns",
    },
    typeColors: {
      units: "bg-red-900/40 text-red-400",
      wielders: "bg-amber-900/40 text-amber-400",
      spells: "bg-indigo-900/40 text-indigo-400",
      artifacts: "bg-purple-900/40 text-purple-400",
      skills: "bg-emerald-900/40 text-emerald-400",
      factions: "bg-yellow-900/40 text-yellow-400",
      buildings: "bg-orange-900/40 text-orange-400",
      random_events: "bg-teal-900/40 text-teal-400",
    },
    languageCount: 13,
  },
});
