import { resolveAppConfig } from "@repo/lib";

export const soulsRemnant = resolveAppConfig({
  name: "souls-remnant",
  supportedLocales: [
    "en",
    "de",
    "es",
    "es-MX",
    "fr",
    "id",
    "it",
    "ja",
    "ko",
    "pl",
    "pt-BR",
    "ru",
    "th",
    "tr",
    "vi",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  // No manual "/maps/..." internalLinks — the home page auto-generates richer
  // map cards (preview + live counts) for the Surface and Caves maps.
  internalLinks: [
    {
      title: "config.internalLinks.items.title",
      description: "config.internalLinks.items.description",
      href: "/db/items",
      iconName: "Gift",
      linkText: "config.internalLinks.items.linkText",
    },
    {
      title: "config.internalLinks.equipment.title",
      description: "config.internalLinks.equipment.description",
      href: "/db/equipment",
      iconName: "Shield",
      linkText: "config.internalLinks.equipment.linkText",
    },
    {
      title: "config.internalLinks.monsters.title",
      description: "config.internalLinks.monsters.description",
      href: "/db/monsters",
      iconName: "Bug",
      linkText: "config.internalLinks.monsters.linkText",
    },
    {
      title: "config.internalLinks.skills.title",
      description: "config.internalLinks.skills.description",
      href: "/db/skills",
      iconName: "Sparkles",
      linkText: "config.internalLinks.skills.linkText",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: ["World Map", "Monsters", "Items", "Equipment", "Skills"],
  topFilters: ["boss_arena", "hubs", "deep_caves"],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/items",
        type: "items",
        titleKey: "config.internalLinks.items.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.items.description",
      },
      {
        href: "/db/equipment",
        type: "equipment",
        titleKey: "config.internalLinks.equipment.title",
        titleFallback: "Equipment",
        icon: "🛡️",
        description: "config.db.equipment.description",
      },
      {
        href: "/db/monsters",
        type: "monsters",
        titleKey: "config.internalLinks.monsters.title",
        titleFallback: "Monsters",
        icon: "👾",
        description: "config.db.monsters.description",
      },
      {
        href: "/db/skills",
        type: "skills",
        titleKey: "config.internalLinks.skills.title",
        titleFallback: "Skills",
        icon: "✨",
        description: "config.db.skills.description",
      },
      {
        href: "/db/buffs",
        type: "buffs",
        titleKey: "config.db.buffs.title",
        titleFallback: "Status Effects",
        icon: "🌀",
        description: "config.db.buffs.description",
      },
      {
        href: "/db/maps",
        type: "maps",
        titleKey: "config.db.maps.title",
        titleFallback: "Maps",
        icon: "🗺️",
        description: "config.db.maps.description",
      },
      {
        href: "/db/npcs",
        type: "npcs",
        titleKey: "config.db.npcs.title",
        titleFallback: "NPCs",
        icon: "🧑‍🌾",
        description: "config.db.npcs.description",
      },
      {
        href: "/db/dungeons",
        type: "dungeons",
        titleKey: "config.db.dungeons.title",
        titleFallback: "Dungeons",
        icon: "🏰",
        description: "config.db.dungeons.description",
      },
      {
        href: "/db/quests",
        type: "quests",
        titleKey: "config.db.quests.title",
        titleFallback: "Quests",
        icon: "📜",
        description: "config.db.quests.description",
      },
      {
        href: "/db/game-modes",
        type: "game-modes",
        titleKey: "config.db.game-modes.title",
        titleFallback: "Game Modes",
        icon: "🎮",
        description: "config.db.game-modes.description",
      },
    ],
    typeLabels: {
      items: "config.db.typeLabels.items",
      equipment: "config.db.typeLabels.equipment",
      monsters: "config.db.typeLabels.monsters",
      skills: "config.db.typeLabels.skills",
      buffs: "config.db.typeLabels.buffs",
      maps: "config.db.typeLabels.maps",
      npcs: "config.db.typeLabels.npcs",
      dungeons: "config.db.typeLabels.dungeons",
      quests: "config.db.typeLabels.quests",
      "game-modes": "config.db.typeLabels.game-modes",
    },
  },
});
