import { resolveAppConfig } from "@repo/lib";

export const theFirstDescendant = resolveAppConfig({
  name: "the-first-descendant",
  // The client ships twelve text languages (Data/DataCenter/LocalizedString M1String*Json).
  supportedLocales: [
    "en",
    "de",
    "fr",
    "es",
    "it",
    "pl",
    "pt-BR",
    "ru",
    "ja",
    "ko",
    "zh-CN",
    "zh-TW",
  ],
  // No companion app: online-only client with anti-cheat, so there is no live tracking.
  appUrl: null,
  // No internalLinks for maps: the home page auto-generates map cards from the tiles.
  internalLinks: [
    {
      title: "config.internalLinks.amorphous.title",
      description: "config.internalLinks.amorphous.description",
      href: "/db/amorphous",
      iconName: "Gift",
      linkText: "config.internalLinks.amorphous.linkText",
    },
    {
      title: "config.internalLinks.descendants.title",
      description: "config.internalLinks.descendants.description",
      href: "/db/descendants",
      iconName: "Users",
      linkText: "config.internalLinks.descendants.linkText",
    },
    {
      title: "config.internalLinks.weapons.title",
      description: "config.internalLinks.weapons.description",
      href: "/db/weapons",
      iconName: "Axe",
      linkText: "config.internalLinks.weapons.linkText",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
    {
      href: "/activities-tracker",
      title: "activities.navTitle",
      description: "activities.navDescription",
      linkText: "activities.navLinkText",
      iconName: "Activity",
    },
  ],
  promoLinks: [],
  externalLinks: [],
  keywords: [
    "Encrypted Vault",
    "Void Fragment",
    "Void Fusion Reactor",
    "Battlefield Missions",
    "Calling of the Descendant",
    "Special Operations",
    "Camps",
    "Albion",
    "Kingston",
    "Sterile Land",
    "Vespers",
    "Echo Swamp",
    "Agna Desert",
    "White-night Gulch",
    "Hagios",
    "Fortress",
    "Axion Plains",
  ],
  topFilters: ["encrypted_vault", "void_fusion_reactor", "camp"],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/descendants",
        type: "descendants",
        titleKey: "config.internalLinks.descendants.title",
        titleFallback: "Descendants",
        icon: "🧬",
        description: "config.db.descendants.description",
      },
      {
        href: "/db/abilities",
        type: "abilities",
        titleKey: "config.db.abilities.title",
        titleFallback: "Abilities",
        groupRefs: "transcendentModules",
        icon: "✨",
        description: "config.db.abilities.description",
      },
      {
        href: "/db/weapons",
        type: "weapons",
        titleKey: "config.internalLinks.weapons.title",
        titleFallback: "Weapons",
        icon: "🔫",
        description: "config.db.weapons.description",
      },
      {
        href: "/db/modules",
        type: "modules",
        titleKey: "config.db.modules.title",
        titleFallback: "Modules",
        icon: "🧩",
        description: "config.db.modules.description",
      },
      {
        href: "/db/reactors",
        type: "reactors",
        titleKey: "config.db.reactors.title",
        titleFallback: "Reactors",
        icon: "⚛️",
        description: "config.db.reactors.description",
      },
      {
        href: "/db/components",
        type: "components",
        titleKey: "config.db.components.title",
        titleFallback: "External Components",
        icon: "🛡️",
        description: "config.db.components.description",
      },
      {
        href: "/db/amorphous",
        type: "amorphous",
        titleKey: "config.db.amorphous.title",
        titleFallback: "Amorphous Materials & Loot",
        icon: "🎁",
        description: "config.db.amorphous.description",
      },
      {
        href: "/db/materials",
        type: "materials",
        titleKey: "config.db.materials.title",
        titleFallback: "Materials & Consumables",
        icon: "⚗️",
        description: "config.db.materials.description",
      },
      {
        href: "/db/bosses",
        type: "bosses",
        titleKey: "config.db.bosses.title",
        titleFallback: "Bosses",
        icon: "💀",
        description: "config.db.bosses.description",
      },
      {
        href: "/db/records",
        type: "records",
        titleKey: "config.db.records.title",
        titleFallback: "Records",
        icon: "📜",
        description: "config.db.records.description",
      },
      {
        href: "/db/arche-tuning",
        type: "arche-tuning",
        titleKey: "config.db.arche-tuning.title",
        titleFallback: "Arche Tuning",
        icon: "🔷",
        description: "config.db.arche-tuning.description",
      },
      {
        href: "/db/reinforcements",
        type: "reinforcements",
        titleKey: "config.db.reinforcements.title",
        titleFallback: "Inversion Reinforcements",
        icon: "🔺",
        description: "config.db.reinforcements.description",
      },
      {
        href: "/db/skins",
        type: "skins",
        titleKey: "config.db.skins.title",
        titleFallback: "Skins & Customization",
        icon: "🎨",
        description: "config.db.skins.description",
      },
      {
        href: "/db/fellows",
        type: "fellows",
        titleKey: "config.db.fellows.title",
        titleFallback: "Fellows",
        icon: "🐕",
        description: "config.db.fellows.description",
      },
      {
        href: "/db/vehicles",
        type: "vehicles",
        titleKey: "config.db.vehicles.title",
        titleFallback: "Vehicles",
        icon: "🏍️",
        description: "config.db.vehicles.description",
      },
    ],
    typeLabels: {
      descendants: "config.db.typeLabels.descendants",
      abilities: "config.db.typeLabels.abilities",
      weapons: "config.db.typeLabels.weapons",
      modules: "config.db.typeLabels.modules",
      reactors: "config.db.typeLabels.reactors",
      components: "config.db.typeLabels.components",
      amorphous: "config.db.typeLabels.amorphous",
      materials: "config.db.typeLabels.materials",
      bosses: "config.db.typeLabels.bosses",
      records: "config.db.typeLabels.records",
      "arche-tuning": "config.db.typeLabels.arche-tuning",
      reinforcements: "config.db.typeLabels.reinforcements",
      skins: "config.db.typeLabels.skins",
      fellows: "config.db.typeLabels.fellows",
      vehicles: "config.db.typeLabels.vehicles",
    },
  },
});
