import { resolveAppConfig } from "@repo/lib";

export const valheim = resolveAppConfig({
  name: "valheim",
  supportedLocales: [
    "en",
    "cs",
    "de",
    "es",
    "fr",
    "hu",
    "it",
    "ja",
    "ko",
    "pl",
    "pt-BR",
    "ru",
    "th",
    "tr",
    "uk",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: null,
  internalLinks: [],
  promoLinks: [],
  // Partner link — keep it next to our own /db (gaming.tools is our most important partner).
  externalLinks: [
    {
      href: "https://valheim.gaming.tools",
      title: "config.externalLinks.valheim.title",
    },
  ],
  keywords: [
    "Seed Map",
    "World Seed",
    "Boss Locations",
    "Haldor",
    "Hildir",
    "Bog Witch",
    "Burial Chambers",
    "Troll Cave",
    "Sunken Crypts",
    "Infested Mine",
    "Runestones",
    "Biomes",
  ],
  topFilters: [
    "eikthyr",
    "haldor",
    "burial_chambers",
    "troll_cave",
    "runestone",
  ],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "config.db.inventory.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.inventory.description",
      },
      {
        href: "/db/bestiary",
        type: "bestiary",
        titleKey: "config.db.bestiary.title",
        titleFallback: "Bestiary",
        icon: "🐺",
        description: "config.db.bestiary.description",
      },
      {
        href: "/db/building",
        type: "building",
        titleKey: "config.db.building.title",
        titleFallback: "Building",
        icon: "🔨",
        description: "config.db.building.description",
      },
      {
        href: "/db/locations",
        type: "locations",
        titleKey: "config.db.locations.title",
        titleFallback: "Locations",
        icon: "🗺️",
        description: "config.db.locations.description",
      },
      {
        href: "/db/biomes",
        type: "biomes",
        titleKey: "config.db.biomes.title",
        titleFallback: "Biomes",
        icon: "🌲",
        description: "config.db.biomes.description",
      },
      {
        href: "/db/skills",
        type: "skills",
        titleKey: "config.db.skills.title",
        titleFallback: "Skills",
        icon: "⚔️",
        description: "config.db.skills.description",
      },
      {
        href: "/db/lore",
        type: "lore",
        titleKey: "config.db.lore.title",
        titleFallback: "Lore",
        icon: "📜",
        description: "config.db.lore.description",
      },
    ],
    typeLabels: {
      inventory: "config.db.typeLabels.inventory",
      bestiary: "config.db.typeLabels.bestiary",
      building: "config.db.typeLabels.building",
      locations: "config.db.typeLabels.locations",
      biomes: "config.db.typeLabels.biomes",
      skills: "config.db.typeLabels.skills",
      lore: "config.db.typeLabels.lore",
    },
  },
});
