import { resolveAppConfig } from "@repo/lib";

export const welcomeToElderfield = resolveAppConfig({
  name: "welcome-to-elderfield",
  // Matches the dicts the data-mining script emits from the game's Hendrix
  // Localization CSV (en + the 6 shipped translations).
  supportedLocales: ["en", "de", "es", "fr", "pt-BR", "ru", "zh-CN"],
  appUrl: null,
  withoutLiveMode: true,
  // No manual "/maps/..." internalLinks — the home page auto-generates the map
  // cards from version.data.tiles. The links below point at the database.
  internalLinks: [
    {
      title: "config.internalLinks.villagers.title",
      description: "config.internalLinks.villagers.description",
      href: "/db/villagers",
      iconName: "Heart",
      linkText: "config.internalLinks.villagers.linkText",
    },
    {
      title: "config.internalLinks.items.title",
      description: "config.internalLinks.items.description",
      href: "/db/items",
      iconName: "Gift",
      linkText: "config.internalLinks.items.linkText",
    },
    {
      title: "config.internalLinks.equipment.title",
      description: "config.internalLinks.equipment.description",
      href: "/db/equipment",
      iconName: "Shield",
      linkText: "config.internalLinks.equipment.linkText",
    },
    {
      title: "config.internalLinks.recipes.title",
      description: "config.internalLinks.recipes.description",
      href: "/db/recipes",
      iconName: "BookOpen",
      linkText: "config.internalLinks.recipes.linkText",
    },
    {
      title: "config.internalLinks.fish.title",
      description: "config.internalLinks.fish.description",
      href: "/db/fish",
      iconName: "Fish",
      linkText: "config.internalLinks.fish.linkText",
    },
    {
      title: "config.internalLinks.bestiary.title",
      description: "config.internalLinks.bestiary.description",
      href: "/db/bestiary",
      iconName: "Bug",
      linkText: "config.internalLinks.bestiary.linkText",
    },
    {
      title: "checklist.navTitle",
      description: "checklist.navDescription",
      href: "/checklist",
      iconName: "SquareCheckBig",
      linkText: "checklist.navLinkText",
    },
    {
      title: "crafting.navTitle",
      description: "crafting.navDescription",
      href: "/crafting",
      iconName: "Hammer",
      linkText: "crafting.navLinkText",
    },
  ],
  externalLinks: [],
  keywords: ["Mysteries", "Villager Gifts", "Fishing", "Doors & Exits"],
  topFilters: [
    "door",
    "mystery",
    "god_shrine",
    "treasure_dig",
    "villager_sam",
    "shop",
  ],
  db: {
    // Collection checklists (/checklist, /checklist/<section>).
    checklists: [{ section: "fish" }, { section: "bestiary" }],
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/villagers",
        type: "villagers",
        titleKey: "config.internalLinks.villagers.title",
        titleFallback: "Villagers",
        icon: "💕",
        description: "config.db.villagers.description",
      },
      {
        href: "/db/items",
        type: "items",
        titleKey: "config.internalLinks.items.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.items.description",
      },
      {
        href: "/db/equipment",
        type: "equipment",
        titleKey: "config.internalLinks.equipment.title",
        titleFallback: "Equipment",
        icon: "🗡️",
        description: "config.db.equipment.description",
      },
      {
        href: "/db/recipes",
        type: "recipes",
        titleKey: "config.internalLinks.recipes.title",
        titleFallback: "Recipes",
        icon: "🍲",
        description: "config.db.recipes.description",
      },
      {
        href: "/db/fish",
        type: "fish",
        titleKey: "config.internalLinks.fish.title",
        titleFallback: "Fish",
        icon: "🐟",
        description: "config.db.fish.description",
      },
      {
        href: "/db/bestiary",
        type: "bestiary",
        titleKey: "config.internalLinks.bestiary.title",
        titleFallback: "Bestiary",
        icon: "👹",
        description: "config.db.bestiary.description",
      },
      {
        href: "/db/quests",
        type: "quests",
        titleKey: "config.db.quests.title",
        titleFallback: "Tasks",
        icon: "📜",
        description: "config.db.quests.description",
      },
      {
        href: "/db/shops",
        type: "shops",
        titleKey: "config.db.shops.title",
        titleFallback: "Shops",
        icon: "🛒",
        description: "config.db.shops.description",
      },
      {
        href: "/db/skills",
        type: "skills",
        titleKey: "config.db.skills.title",
        titleFallback: "Skills & Rituals",
        icon: "✨",
        description: "config.db.skills.description",
      },
      {
        href: "/db/states",
        type: "states",
        titleKey: "config.db.states.title",
        titleFallback: "Blessings & Curses",
        icon: "🌀",
        description: "config.db.states.description",
      },
      {
        href: "/db/locations",
        type: "locations",
        titleKey: "config.db.locations.title",
        titleFallback: "Locations",
        icon: "🗺️",
        description: "config.db.locations.description",
      },
    ],
    typeLabels: {
      villagers: "config.db.typeLabels.villagers",
      items: "config.db.typeLabels.items",
      equipment: "config.db.typeLabels.equipment",
      recipes: "config.db.typeLabels.recipes",
      fish: "config.db.typeLabels.fish",
      bestiary: "config.db.typeLabels.bestiary",
      quests: "config.db.typeLabels.quests",
      shops: "config.db.typeLabels.shops",
      skills: "config.db.typeLabels.skills",
      states: "config.db.typeLabels.states",
      locations: "config.db.typeLabels.locations",
    },
  },
});
