import { resolveAppConfig } from "@repo/lib";

export const wutheringWaves = resolveAppConfig({
  name: "wuthering-waves",
  supportedLocales: [
    "en",
    "de",
    "es",
    "fr",
    "ja",
    "ko",
    "pt",
    "th",
    "zh-CN",
    "zh-TW",
  ],
  appUrl: "https://www.th.gl/companion-app",
  // Maps are NOT listed here: the home page auto-generates a card for each map
  // in version.data.tiles (Overworld, Lahai-Roi, Honami City, etc.).
  internalLinks: [
    {
      href: "/activities-tracker",
      title: "activities.navTitle",
      description: "activities.navDescription",
      linkText: "activities.navLinkText",
      iconName: "Activity",
    },
  ],
  externalLinks: [],
  keywords: [
    "Echoes",
    "Waveplate Activities",
    "Tidal Heritage",
    "Collectibles",
  ],
  topFilters: ["Treasure005", "branch3.0_693_Treasure_3_4"],
  db: {
    heroSubtitle: "config.db.heroSubtitle",
    searchPlaceholder: "config.db.searchPlaceholder",
    sectionsInNav: true,
    homeSections: [
      {
        href: "/db/resonators",
        type: "resonators",
        titleKey: "config.db.resonators.title",
        titleFallback: "Resonators",
        icon: "🧝",
        description: "config.db.resonators.description",
      },
      {
        href: "/db/weapons",
        type: "weapons",
        titleKey: "config.db.weapons.title",
        titleFallback: "Weapons",
        icon: "⚔️",
        description: "config.db.weapons.description",
      },
      {
        href: "/db/echoes",
        type: "echoes",
        titleKey: "config.db.echoes.title",
        titleFallback: "Echoes",
        icon: "👁️",
        description: "config.db.echoes.description",
      },
      {
        href: "/db/sonatas",
        type: "sonatas",
        titleKey: "config.db.sonatas.title",
        titleFallback: "Sonatas",
        icon: "🎼",
        description: "config.db.sonatas.description",
      },
      {
        href: "/db/enemies",
        type: "enemies",
        titleKey: "config.db.enemies.title",
        titleFallback: "Enemies",
        icon: "💀",
        description: "config.db.enemies.description",
      },
      {
        href: "/db/inventory",
        type: "inventory",
        titleKey: "config.db.inventory.title",
        titleFallback: "Items",
        icon: "🎒",
        description: "config.db.inventory.description",
      },
    ],
    typeLabels: {
      resonators: "config.db.typeLabels.resonators",
      weapons: "config.db.typeLabels.weapons",
      echoes: "config.db.typeLabels.echoes",
      sonatas: "config.db.typeLabels.sonatas",
      enemies: "config.db.typeLabels.enemies",
      inventory: "config.db.typeLabels.inventory",
    },
  },
});
