export function isDebug() {
  return localStorage.getItem("DEBUG") === "true";
}

export const isOverwolf =
  typeof window !== "undefined" &&
  // @ts-expect-error
  typeof window.___overwolf___ !== "undefined";

export const BLACKLISTED_TYPES = [
  // "BP_Creature_NPC_Puck_C",
  "StaticMeshActor",
  "DefaultPhysicsVolume",
  "BP_PlayerController_C",
  "BP_PlayerCameraManager_C",
  "HUD_CommonNWX_C",
  "BP_GameState_C",
  "BP_Spectator_C",
  "WindDirectionalSource",
  "BP_PlayerInputHandler_C",
  "StreamingLevelProxyActor",
  "BP_StreamingLevelProxy_C",
  "BP_PlayerState_C",
  "BP_Structure_Constructed_C",
  "BP_Structure_DeathChest_C",
  "BP_POIConfig_C",
  "BP_StructureBuilder_C",
  "BP_Proof_Garden_TEST_02_C",
  "BP_StructurePartProxy_C",
  "BP_UI_ThirdPersonLights_C",
  "BP_Character_C",
  "BP_Weapon_Base_C",
  "BP_EquippableItemBase_C",
  "BP_Encounter_Gym_C",
  "BP_EncounterMusic_C",
  "BPP_SL_CH_0_NightmareRealm_C",
  "NWXPlayerStart",
  "PointLight",
  "NiagaraActor",
  "SpotLight",
  "EncounterConfig",
  "BP_AVFXPlacer_Cavern_Bat_Cannon_C",
  "BP_NightmareIntroAnimTrigger_C",
  "Actor",
  "BP_PortalArchVFX_C",
  "BP_AKEventTrigger_NightmareMeteor_C",
  "BP_DialogueEventTrigger_C",
  "BP_VST_ForestMid06_C",
  "BP_VST_Forest01_C",
  "CullDistanceVolume",
  "NavModifierVolume",
  "Audio_ML_FRT_NST_Cave_03_31m_C",
  "BP_AVFXPlacer_Cavern_Fog_C",
  "BP_AVFXPlacer_Cavern_FallingRocks_C",
  "BP_Cave_EmissiveLight_01_C",
  "InstancedFoliageActor",
  "BP_CaveCliffside_AVFXPlane_C",
  "BP_VST_ForestMid01_C",
  "BP_VST_ForestMid03_C",
  "BP_VST_ForestMid02_C",
  "BP_VST_ForestMid04_C",
  "BP_FRT_ScatterGrass01_C",
  "BP_VST_ForestMid05_C",
  "BP_VST_Forest02_C",
  "Audio_ML_FRT_NST_Cave_04_31m_C",
  "Audio_ML_FRT_NST_Cave_05_31m_C",
  "DecalActor",
  "BP_Waterfall_Volume_C",
  "Audio_ML_FRT_WTF_Waterfall08_10m_C",
  "BP_MapPinClientActor_C",
  "BP_AoePayload_Dispellable_Miasma_Spawn_Cloud_C",
  "BP_ResourceNode_IIM_C",
  "BP_SplineRoad_C",
  "BP_AVFXPlacer_AmbientDrifts_C",
  "BP_AVFXPlacer_CAM_ENV_C",
  "BP_AVFXPlacer_FallingRocks_C",
  "BP_AVFXPlacer_Birds_C",
  "BP_AVFXPlacer_Dust_C",
  "BP_AVFXPlacer_Fishes_C",
  "BP_AVFXPlacer_Fog_C",
  "BP_CompassMarker_C",
  "BP_Tool_Lantern_C",
  "ActivationVolume",
  "PostProcessVolume",
  "ImpulseVolume",
  "NavMeshBoundsVolume",
  "CamerActor",
  "CineCamerActor",
  "BlockingVolume",
  "BP_FluxNiagaraActor_C",
];
