import { DATA_FORGE_CDN_URL, fetchJsonWithMemoryCache } from "./config";

/**
 * Written guides (editorial "how to" articles) generated by data-forge from the game's
 * own data — `data-mining/src/<game>/guides/*.md` → `config/guides.json` (index) +
 * `config/guides/<slug>.json`. Every claim in them is backed by a cited game-data fact;
 * see data-forge `docs/WRITTEN_GUIDES.md`.
 */
export type GuideBlock =
  | { type: "md"; md: string }
  | { type: "map"; types: string[] }
  | { type: "recipe"; section: string; id: string }
  | { type: "item"; section: string; id: string };

export type GuideIndexEntry = {
  slug: string;
  title: string;
  description: string;
  subject: { section: string; id: string };
  /** `<section>/<id>` of every DB entry the guide is about or links */
  entities: string[];
  /** ISO date */
  updated: string;
};

export type Guide = GuideIndexEntry & {
  keywords: string[];
  blocks: GuideBlock[];
};

// Guides change independently of a mining run (no content hash), so they use the
// regular memory-cache TTL; in dev always re-read.
const ttlMs = process.env.NODE_ENV === "development" ? 0 : undefined;

/** All written guides of a game; [] when it has none. */
export async function fetchGuidesIndex(
  appName: string,
): Promise<GuideIndexEntry[]> {
  return fetchJsonWithMemoryCache<GuideIndexEntry[]>(
    `${DATA_FORGE_CDN_URL}/${appName}/config/guides.json`,
    { onNotFound: () => [], ttlMs },
  ).catch(() => []);
}

/** One guide by slug, or null. */
export async function fetchGuide(
  appName: string,
  slug: string,
): Promise<Guide | null> {
  const index = await fetchGuidesIndex(appName);
  if (!index.some((g) => g.slug === slug)) return null;
  return fetchJsonWithMemoryCache<Guide | null>(
    `${DATA_FORGE_CDN_URL}/${appName}/config/guides/${slug}.json`,
    { onNotFound: () => null, ttlMs },
  );
}

/** Guides about or linking a DB entry, the guide whose subject it is first. */
export function guidesForEntry(
  index: GuideIndexEntry[],
  section: string,
  id: string,
): GuideIndexEntry[] {
  const key = `${section}/${id}`;
  return index
    .filter((g) => g.entities.includes(key))
    .sort(
      (a, b) =>
        Number(`${b.subject.section}/${b.subject.id}` === key) -
        Number(`${a.subject.section}/${a.subject.id}` === key),
    );
}

/** A written guide as a header/footer nav entry. */
export type GuideNavLink = { href: string; label: string };

/**
 * Nav entries for the "Guides" menu: the first `max` written guides with a short
 * label. Titles are "How to Make X in <Game Title>"; inside the game's own Guides
 * menu only "X" carries information, so the "How to Make/Get/Find (a/the)" head and
 * the " in <Game Title>" tail are dropped (other title shapes stay as they are).
 */
export function guideNavLinks(
  index: GuideIndexEntry[],
  gameTitle: string,
  max = 10,
): GuideNavLink[] {
  const tail = ` in ${gameTitle}`;
  return index
    .slice(0, max)
    .map((g) => {
      let label = g.title.endsWith(tail)
        ? g.title.slice(0, -tail.length)
        : g.title;
      label = label.replace(
        /^How to (?:Make|Get|Find|Craft) (?:an? |the )?/i,
        "",
      );
      return { href: `/guides/${g.slug}`, label };
    })
    .sort((a, b) => a.label.localeCompare(b.label));
}
