name: Avowed Preview

on:
  push:
    paths:
      - "apps/avowed-overwolf/manifest.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Build Overwolf app
        run: bunx turbo run build --filter=avowed-overwolf...
      - name: Release Overwolf app
        env:
          OW_CLI_EMAIL: ${{ secrets.OW_CLI_EMAIL }}
          OW_CLI_API_KEY: ${{ secrets.OW_CLI_API_KEY }}
          PREVIEW_ACCESS_CHANNEL_ID: 1030
        run: bunx turbo run release --filter=avowed-overwolf...
