name: Once Human Production

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Build Overwolf app
        run: bunx turbo run build --filter=once-human-overwolf...
      - name: Release Overwolf app
        env:
          OW_CLI_EMAIL: ${{ secrets.OW_CLI_EMAIL }}
          OW_CLI_API_KEY: ${{ secrets.OW_CLI_API_KEY }}
        run: bunx turbo run release --filter=once-human-overwolf...
