name: Palworld Preview

on:
  push:
    paths:
      - "apps/palworld-overwolf/manifest.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - name: Build Overwolf app
        run: bun run build:palworld-overwolf
      - name: Release Overwolf app
        env:
          OW_CLI_EMAIL: ${{ secrets.OW_CLI_EMAIL }}
          OW_CLI_API_KEY: ${{ secrets.OW_CLI_API_KEY }}
          PREVIEW_ACCESS_CHANNEL_ID: 751
        run: bun run release:palworld-overwolf
